package com.wasimaster.wmkeyboard.core.emoji

/**
 * Skin-tone (Fitzpatrick modifier) variants for emoji that support them.
 *
 * Detection uses the Unicode Emoji_Modifier_Base ranges, so no per-emoji
 * data is needed. Variants are generated by inserting the modifier right
 * after the base code point (keeping any ZWJ tail intact), which is how
 * single-person sequences are composed. Multi-person ZWJ sequences with
 * more than one modifier base are left alone — per-person tones are out
 * of scope.
 */
object EmojiVariants {

    private val MODIFIERS = listOf(0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF)

    /** Unicode 15 Emoji_Modifier_Base ranges. */
    private val MODIFIER_BASES = listOf(
        0x261D..0x261D, 0x26F9..0x26F9, 0x270A..0x270D,
        0x1F385..0x1F385, 0x1F3C2..0x1F3C4, 0x1F3C7..0x1F3C7, 0x1F3CA..0x1F3CC,
        0x1F442..0x1F443, 0x1F446..0x1F450, 0x1F466..0x1F478, 0x1F47C..0x1F47C,
        0x1F481..0x1F483, 0x1F485..0x1F487, 0x1F48F..0x1F48F, 0x1F491..0x1F491,
        0x1F4AA..0x1F4AA, 0x1F574..0x1F575, 0x1F57A..0x1F57A, 0x1F590..0x1F590,
        0x1F595..0x1F596, 0x1F645..0x1F647, 0x1F64B..0x1F64F, 0x1F6A3..0x1F6A3,
        0x1F6B4..0x1F6B6, 0x1F6C0..0x1F6C0, 0x1F6CC..0x1F6CC, 0x1F90C..0x1F90C,
        0x1F90F..0x1F90F, 0x1F918..0x1F91F, 0x1F926..0x1F926, 0x1F930..0x1F939,
        0x1F93C..0x1F93E, 0x1F977..0x1F977, 0x1F9B5..0x1F9B6, 0x1F9B8..0x1F9B9,
        0x1F9BB..0x1F9BB, 0x1F9CD..0x1F9DD, 0x1FAC3..0x1FAC5, 0x1FAF0..0x1FAF8,
    )

    private const val VARIATION_SELECTOR = 0xFE0F

    private fun isModifierBase(codePoint: Int) = MODIFIER_BASES.any { codePoint in it }

    private fun isModifier(codePoint: Int) = codePoint in 0x1F3FB..0x1F3FF

    /** True when [emoji] can take a skin-tone modifier. */
    fun supportsSkinTones(emoji: String): Boolean {
        if (emoji.isEmpty()) return false
        val codePoints = emoji.codePoints().toArray()
        // Exactly one modifier base and no modifier already applied →
        // a plain single-person emoji we can tone.
        return codePoints.count { isModifierBase(it) } == 1 && codePoints.none { isModifier(it) }
    }

    /**
     * The neutral emoji plus its five toned variants, or just [emoji]
     * when tones are not supported.
     */
    fun variants(emoji: String): List<String> {
        if (!supportsSkinTones(emoji)) return listOf(emoji)
        val codePoints = emoji.codePoints().toArray()
        val baseIndex = codePoints.indexOfFirst { isModifierBase(it) }
        return buildList {
            add(emoji)
            for (modifier in MODIFIERS) {
                val sb = StringBuilder()
                codePoints.forEachIndexed { index, cp ->
                    // An FE0F presentation selector after the base is
                    // replaced by the tone modifier (RGI form).
                    if (index == baseIndex + 1 && cp == VARIATION_SELECTOR) return@forEachIndexed
                    sb.appendCodePoint(cp)
                    if (index == baseIndex) sb.appendCodePoint(modifier)
                }
                add(sb.toString())
            }
        }
    }
}
