package com.wasimaster.wmkeyboard.core.emoji

import java.io.InputStream

/**
 * Word → emoji predictions taken from GitHub's gemoji data: its single-word
 * shortcodes (`birthday` → 🎂) and its hand-picked tags (`hooray` → 🎉).
 *
 * The same source as [EmojiShortcodes], read the other way round. A shortcode
 * answers "what did the user name?"; a trigger answers "what did the user
 * *mean*?" — and gemoji's own tags are already written as the second question,
 * which is why they beat anything derived from the Unicode keyword lists (the
 * CLDR keywords for 🎉 include "party popper" and "popper", never "hooray").
 *
 * Data comes from the bundled `emoji/triggers.tsv`, generated by
 * `tools/emoji/generate_gemoji.py`. The generator drops names under three
 * characters, so the two-letter flag codes never fire on ordinary words.
 */
class EmojiTriggers private constructor(private val byWord: Map<String, List<String>>) {

    val isEmpty: Boolean get() = byWord.isEmpty()

    /** Emoji for an exact word, best first; empty when nothing matches. */
    fun of(word: String): List<String> = byWord[word.trim().lowercase()].orEmpty()

    companion object {

        val EMPTY = EmojiTriggers(emptyMap())

        /** Format: `word<TAB>emoji,emoji,...`, one per line, `# ` comments. */
        fun load(stream: InputStream): EmojiTriggers {
            val byWord = HashMap<String, List<String>>()
            stream.bufferedReader().useLines { lines ->
                for (line in lines) {
                    if (line.isBlank() || line.startsWith("# ")) continue
                    val tab = line.indexOf('\t')
                    if (tab <= 0) continue
                    val word = line.substring(0, tab).trim().lowercase()
                    val emojis = line.substring(tab + 1)
                        .split(',')
                        .map { it.trim() }
                        .filter { it.isNotEmpty() }
                    if (word.isNotEmpty() && emojis.isNotEmpty()) byWord[word] = emojis
                }
            }
            return EmojiTriggers(byWord)
        }
    }
}
