// Regenerated by record.sh (gen_manifest) — lists files present in public/clips.
// Scenes fall back to a placeholder panel for clips not yet captured.
export const AVAILABLE_CLIPS: string[] = [
  "addons.mp4",
  "calc.mp4",
  "emoji.mp4",
  "fieldkinds.mp4",
  "glide.mp4",
  "modes.mp4",
  "themes.mp4",
  "toolbox.mp4",
  "voice.mp4",
];

// Set to a filename in public/ (e.g. "music.mp3") to mix a soundtrack.
export const MUSIC: string | null = null;
