package com.wasimaster.wmkeyboard.ime.ui

import androidx.compose.runtime.compositionLocalOf
import com.wasimaster.wmkeyboard.ime.CaptureSelectionAction

/**
 * The keyboard's own text fields, as the UI sees them (#161).
 *
 * The service owns the buffers and the caret (see `CaptureField.kt`); this is
 * the pair of seams the panels need: where to draw the caret, and what a tap
 * or a strip pick should tell the service.
 */

/**
 * Where the caret stands in whichever keyboard-owned field has the keys, and
 * how a tap moves it.
 *
 * A composition local rather than a parameter because [SearchQueryText] is
 * called from nine panels and the caret is a property of *the* focused field —
 * there is only ever one — rather than of any particular call site. [at] is a
 * UTF-16 index into that field's text; [onCaretTap] is the service's
 * `onCaptureCaretTap`.
 */
data class CaptureCaretHandle(
    val at: Int,
    val onCaretTap: (Int) -> Unit,
    /** The selection's fixed end; [at] when nothing is selected (#352). */
    val anchor: Int = at,
    /** A long press or a handle drag: the service's `onCaptureSelect(anchor, caret)`. */
    val onSelect: (Int, Int) -> Unit = { _, _ -> },
    /** The selection bar's Cut, Copy, Paste and Select all. */
    val onSelectionAction: (CaptureSelectionAction) -> Unit = {},
) {
    val selectionStart: Int get() = minOf(at, anchor)
    val selectionEnd: Int get() = maxOf(at, anchor)
    val hasSelection: Boolean get() = at != anchor
}

/** The default: no field has the keys, so no caret and nothing to tap. */
val LocalCaptureCaret = compositionLocalOf { CaptureCaretHandle(0, {}) }

/**
 * What a keyboard-owned field's own controls call back into.
 *
 * Bundled into one parameter rather than passed as two, because
 * `KeyboardScreen`'s caller sits against the JVM's 64K method-size ceiling and
 * every parameter costs generated bytecode there — the same reason
 * `ConverterCallbacks` exists.
 */
data class CaptureCallbacks(
    /** A tap landed at this UTF-16 index in the focused field's text. */
    val onCaretTap: (Int) -> Unit = {},
    /** A selection made on the field: anchor, then caret (#352). */
    val onSelect: (Int, Int) -> Unit = { _, _ -> },
    /** Cut, Copy, Paste or Select all from the field's selection bar (#352). */
    val onSelectionAction: (CaptureSelectionAction) -> Unit = {},
    /** A word was picked off the field's own suggestion strip. */
    val onSuggestion: (String) -> Unit = {},
    /**
     * The AI panel's chat mode (#280). It rides here rather than as a parameter
     * of its own for the reason this bundle exists at all, and it belongs: the
     * chat's composer is one of the keyboard's own fields.
     */
    val onAiChat: (com.wasimaster.wmkeyboard.ime.AiChatAction) -> Unit = {},
    /**
     * The KDE Connect panel (#285), here for the same reason: its "type on the
     * computer" line and its address box are keyboard-owned fields. Three
     * entries rather than one sealed type because two of them are on the path
     * of every special-key press and should not allocate to get there.
     */
    val onKde: (com.wasimaster.wmkeyboard.ime.KdeAction) -> Unit = {},
    val onKdeKey: (
        com.wasimaster.wmkeyboard.core.kdeconnect.KdeSpecialKey,
        com.wasimaster.wmkeyboard.core.kdeconnect.KdeModifiers,
    ) -> Unit = { _, _ -> },
    /** Compose mode's Send: the line as one piece of text, with Enter after it or without. */
    val onKdeSend: (Boolean) -> Unit = {},
    /** The microphone on the field's strip, and the line it shows while dictating (#353). */
    val onVoice: (com.wasimaster.wmkeyboard.ime.CaptureVoiceAction) -> Unit = {},
)
