package com.wasimaster.wmkeyboard.ime.ui

import androidx.compose.runtime.compositionLocalOf

/**
 * The keyboard's own text fields, as the UI sees them (#161).
 *
 * The service owns the buffers and the caret (see `CaptureField.kt`); this is
 * the pair of seams the panels need: where to draw the caret, and what a tap
 * or a strip pick should tell the service.
 */

/**
 * Where the caret stands in whichever keyboard-owned field has the keys, and
 * how a tap moves it.
 *
 * A composition local rather than a parameter because [SearchQueryText] is
 * called from nine panels and the caret is a property of *the* focused field —
 * there is only ever one — rather than of any particular call site. [at] is a
 * UTF-16 index into that field's text; [onCaretTap] is the service's
 * `onCaptureCaretTap`.
 */
data class CaptureCaretHandle(val at: Int, val onCaretTap: (Int) -> Unit)

/** The default: no field has the keys, so no caret and nothing to tap. */
val LocalCaptureCaret = compositionLocalOf { CaptureCaretHandle(0) {} }

/**
 * What a keyboard-owned field's own controls call back into.
 *
 * Bundled into one parameter rather than passed as two, because
 * `KeyboardScreen`'s caller sits against the JVM's 64K method-size ceiling and
 * every parameter costs generated bytecode there — the same reason
 * `ConverterCallbacks` exists.
 */
data class CaptureCallbacks(
    /** A tap landed at this UTF-16 index in the focused field's text. */
    val onCaretTap: (Int) -> Unit = {},
    /** A word was picked off the field's own suggestion strip. */
    val onSuggestion: (String) -> Unit = {},
)
