package com.wasimaster.wmkeyboard.core.script

import com.wasimaster.wmkeyboard.core.layout.AssetLayouts
import com.wasimaster.wmkeyboard.core.layout.BuiltInLayouts

/**
 * A language the keyboard offers, and everything language-level that used to hang
 * off the `InputMode`/`KeyboardLanguage` enums: the dictionary folder, the
 * dictation/hint locale, which layouts belong to it, and which script it writes.
 *
 * [id] is a stable BCP-47-ish key ("en", "bn", "fr", "sr-Cyrl" …). It doubles as
 * the on-disk name for the language's imported-dictionary folder, so it must not
 * change once shipped. [layoutIds] are the built-in (or asset) layouts grouped
 * under this language on the Languages screen.
 *
 * [bundledDictionary] is true only where the APK actually ships a word list
 * (English, Bengali). [gestureLexicon] is true only for English, whose glide
 * decoder is bound to the English lexicon; other languages type on the grid but
 * do not gesture until they gain a lexicon.
 */
data class LanguageDef(
    val id: String,
    val displayName: String,
    val englishName: String,
    val script: ScriptId,
    val localeTag: String,
    val layoutIds: List<String>,
    val bundledDictionary: Boolean = false,
    val gestureLexicon: Boolean = false,
    /**
     * The digit glyphs this language draws and types when the numeral-system
     * setting is left on Auto. Defaults to Latin `0-9`; scripts with their own
     * numerals (Arabic, Persian/Urdu, Bengali/Assamese, the Devanagari
     * languages) set their own. A manual override in settings ignores this.
     */
    val numeralSystem: NumeralSystem = NumeralSystem.LATIN,
) {
    /** English-language convenience, preserving the old `InputMode.isEnglish` reads. */
    val isEnglish: Boolean get() = id == "en"
}

/**
 * Every language the keyboard offers. Seeded with the current five; Phase 5
 * expands it toward ~60. Lookups are plain map reads — the exhaustive `when`s the
 * old enums forced (`InputMode.language`, `forMode`, `hintedMode`) collapse to
 * these.
 *
 * [byId] never throws: an id this build does not know (an asset or custom layout
 * from a newer version) resolves to a generic Latin language so the keyboard
 * still draws and types, mirroring how an unknown key action degrades.
 */
object LanguageRegistry {

    val all: List<LanguageDef> = listOf(
        LanguageDef(
            id = "en",
            displayName = "English",
            englishName = "English",
            script = ScriptId.LATIN,
            localeTag = "en-US",
            layoutIds = listOf(
                BuiltInLayouts.QWERTY_ID,
                BuiltInLayouts.AZERTY_ID,
                BuiltInLayouts.DVORAK_ID,
                BuiltInLayouts.COLEMAK_ID,
                BuiltInLayouts.WORKMAN_ID,
                BuiltInLayouts.HALMAK_ID,
            ),
            bundledDictionary = true,
            gestureLexicon = true,
        ),
        LanguageDef(
            id = "bn",
            displayName = "বাংলা · Bangla",
            englishName = "Bangla",
            script = ScriptId.BENGALI,
            localeTag = "bn-BD",
            layoutIds = listOf(BuiltInLayouts.AVRO_ID, BuiltInLayouts.PROBHAT_ID, BuiltInLayouts.JATIYA_ID),
            bundledDictionary = true,
            numeralSystem = NumeralSystem.BENGALI,
        ),
        LanguageDef(
            id = "fr",
            displayName = "Français · French",
            englishName = "French",
            script = ScriptId.LATIN,
            localeTag = "fr-FR",
            layoutIds = listOf(BuiltInLayouts.FRENCH_ID, AssetLayouts.FR_BEPO_ID),
        ),
        LanguageDef(
            id = "de",
            displayName = "Deutsch · German",
            englishName = "German",
            script = ScriptId.LATIN,
            localeTag = "de-DE",
            layoutIds = listOf(BuiltInLayouts.GERMAN_ID, AssetLayouts.DE_SWISS_ID),
        ),
        LanguageDef(
            id = "es",
            displayName = "Español · Spanish",
            englishName = "Spanish",
            script = ScriptId.LATIN,
            localeTag = "es-ES",
            layoutIds = listOf(BuiltInLayouts.SPANISH_ID, AssetLayouts.ES_LATAM_ID),
        ),
        LanguageDef(
            id = "ko",
            displayName = "한국어 · Korean",
            englishName = "Korean",
            script = ScriptId.HANGUL,
            localeTag = "ko-KR",
            layoutIds = listOf(BuiltInLayouts.KOREAN_ID),
        ),
        LanguageDef(
            id = "ru",
            displayName = "Русский · Russian",
            englishName = "Russian",
            script = ScriptId.CYRILLIC,
            localeTag = "ru-RU",
            layoutIds = listOf(BuiltInLayouts.RUSSIAN_ID, AssetLayouts.RU_PHONETIC_ID),
        ),
        LanguageDef(
            id = "ar",
            displayName = "العربية · Arabic",
            englishName = "Arabic",
            script = ScriptId.ARABIC,
            localeTag = "ar-SA",
            layoutIds = listOf(BuiltInLayouts.ARABIC_ID),
            numeralSystem = NumeralSystem.ARABIC_INDIC,
        ),
        LanguageDef(
            id = "el",
            displayName = "Ελληνικά · Greek",
            englishName = "Greek",
            script = ScriptId.GREEK,
            localeTag = "el-GR",
            layoutIds = listOf(BuiltInLayouts.GREEK_ID),
        ),
        LanguageDef(
            id = "he",
            displayName = "עברית · Hebrew",
            englishName = "Hebrew",
            script = ScriptId.HEBREW,
            localeTag = "he-IL",
            layoutIds = listOf(BuiltInLayouts.HEBREW_ID),
        ),
        LanguageDef(
            id = "hi",
            displayName = "हिन्दी · Hindi",
            englishName = "Hindi",
            script = ScriptId.DEVANAGARI,
            localeTag = "hi-IN",
            layoutIds = listOf(BuiltInLayouts.HINDI_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        // Layouts delivered as JSON assets (see AssetLayouts). The language is
        // still Kotlin data — only the key grid moved to a file.
        LanguageDef(
            id = "pt",
            displayName = "Português · Portuguese",
            englishName = "Portuguese",
            script = ScriptId.LATIN,
            localeTag = "pt-BR",
            layoutIds = listOf(AssetLayouts.PT_QWERTY_ID),
        ),
        LanguageDef(
            id = "uk",
            displayName = "Українська · Ukrainian",
            englishName = "Ukrainian",
            script = ScriptId.CYRILLIC,
            localeTag = "uk-UA",
            layoutIds = listOf(AssetLayouts.UK_JCUKEN_ID, AssetLayouts.UK_PHONETIC_ID),
        ),
        LanguageDef(
            id = "it",
            displayName = "Italiano · Italian",
            englishName = "Italian",
            script = ScriptId.LATIN,
            localeTag = "it-IT",
            layoutIds = listOf(AssetLayouts.IT_QWERTY_ID),
        ),
        LanguageDef(
            id = "nl",
            displayName = "Nederlands · Dutch",
            englishName = "Dutch",
            script = ScriptId.LATIN,
            localeTag = "nl-NL",
            layoutIds = listOf(AssetLayouts.NL_QWERTY_ID),
        ),
        LanguageDef(
            id = "pl",
            displayName = "Polski · Polish",
            englishName = "Polish",
            script = ScriptId.LATIN,
            localeTag = "pl-PL",
            layoutIds = listOf(AssetLayouts.PL_QWERTY_ID),
        ),
        LanguageDef(
            id = "sv",
            displayName = "Svenska · Swedish",
            englishName = "Swedish",
            script = ScriptId.LATIN,
            localeTag = "sv-SE",
            layoutIds = listOf(AssetLayouts.SV_QWERTY_ID),
        ),
        LanguageDef(
            id = "sr",
            displayName = "Српски · Serbian",
            englishName = "Serbian",
            script = ScriptId.CYRILLIC,
            localeTag = "sr-RS",
            layoutIds = listOf(AssetLayouts.SR_JCUKEN_ID),
        ),
        LanguageDef(
            id = "bg",
            displayName = "Български · Bulgarian",
            englishName = "Bulgarian",
            script = ScriptId.CYRILLIC,
            localeTag = "bg-BG",
            layoutIds = listOf(AssetLayouts.BG_PHONETIC_ID),
        ),
        LanguageDef(
            id = "ka",
            displayName = "ქართული · Georgian",
            englishName = "Georgian",
            script = ScriptId.GEORGIAN,
            localeTag = "ka-GE",
            layoutIds = listOf(AssetLayouts.KA_QWERTY_ID),
        ),
        LanguageDef(
            id = "cs",
            displayName = "Čeština · Czech",
            englishName = "Czech",
            script = ScriptId.LATIN,
            localeTag = "cs-CZ",
            layoutIds = listOf(AssetLayouts.CS_QWERTZ_ID),
        ),
        LanguageDef(
            id = "sk",
            displayName = "Slovenčina · Slovak",
            englishName = "Slovak",
            script = ScriptId.LATIN,
            localeTag = "sk-SK",
            layoutIds = listOf(AssetLayouts.SK_QWERTZ_ID),
        ),
        LanguageDef(
            id = "ro",
            displayName = "Română · Romanian",
            englishName = "Romanian",
            script = ScriptId.LATIN,
            localeTag = "ro-RO",
            layoutIds = listOf(AssetLayouts.RO_QWERTY_ID),
        ),
        LanguageDef(
            id = "hu",
            displayName = "Magyar · Hungarian",
            englishName = "Hungarian",
            script = ScriptId.LATIN,
            localeTag = "hu-HU",
            layoutIds = listOf(AssetLayouts.HU_QWERTZ_ID),
        ),
        LanguageDef(
            id = "fi",
            displayName = "Suomi · Finnish",
            englishName = "Finnish",
            script = ScriptId.LATIN,
            localeTag = "fi-FI",
            layoutIds = listOf(AssetLayouts.FI_QWERTY_ID),
        ),
        LanguageDef(
            id = "da",
            displayName = "Dansk · Danish",
            englishName = "Danish",
            script = ScriptId.LATIN,
            localeTag = "da-DK",
            layoutIds = listOf(AssetLayouts.DA_QWERTY_ID),
        ),
        LanguageDef(
            id = "nb",
            displayName = "Norsk · Norwegian",
            englishName = "Norwegian",
            script = ScriptId.LATIN,
            localeTag = "nb-NO",
            layoutIds = listOf(AssetLayouts.NB_QWERTY_ID),
        ),
        LanguageDef(
            id = "hr",
            displayName = "Hrvatski · Croatian",
            englishName = "Croatian",
            script = ScriptId.LATIN,
            localeTag = "hr-HR",
            layoutIds = listOf(AssetLayouts.HR_QWERTZ_ID),
        ),
        // Persian reuses the Arabic script (RTL, no case) — a different language
        // on the same ScriptDef, adding the four Perso-Arabic letters پ چ ژ گ.
        LanguageDef(
            id = "fa",
            displayName = "فارسی · Persian",
            englishName = "Persian",
            script = ScriptId.ARABIC,
            localeTag = "fa-IR",
            layoutIds = listOf(AssetLayouts.FA_STANDARD_ID),
            numeralSystem = NumeralSystem.PERSIAN,
        ),
        LanguageDef(
            id = "be",
            displayName = "Беларуская · Belarusian",
            englishName = "Belarusian",
            script = ScriptId.CYRILLIC,
            localeTag = "be-BY",
            layoutIds = listOf(AssetLayouts.BE_JCUKEN_ID),
        ),
        LanguageDef(
            id = "et",
            displayName = "Eesti · Estonian",
            englishName = "Estonian",
            script = ScriptId.LATIN,
            localeTag = "et-EE",
            layoutIds = listOf(AssetLayouts.ET_QWERTY_ID),
        ),
        LanguageDef(
            id = "lt",
            displayName = "Lietuvių · Lithuanian",
            englishName = "Lithuanian",
            script = ScriptId.LATIN,
            localeTag = "lt-LT",
            layoutIds = listOf(AssetLayouts.LT_QWERTY_ID),
        ),
        LanguageDef(
            id = "lv",
            displayName = "Latviešu · Latvian",
            englishName = "Latvian",
            script = ScriptId.LATIN,
            localeTag = "lv-LV",
            layoutIds = listOf(AssetLayouts.LV_QWERTY_ID),
        ),
        LanguageDef(
            id = "sl",
            displayName = "Slovenščina · Slovenian",
            englishName = "Slovenian",
            script = ScriptId.LATIN,
            localeTag = "sl-SI",
            layoutIds = listOf(AssetLayouts.SL_QWERTZ_ID),
        ),
        LanguageDef(
            id = "ur",
            displayName = "اردو · Urdu",
            englishName = "Urdu",
            script = ScriptId.ARABIC,
            localeTag = "ur-PK",
            layoutIds = listOf(AssetLayouts.UR_PHONETIC_ID),
            numeralSystem = NumeralSystem.PERSIAN,
        ),
        LanguageDef(
            id = "ps",
            displayName = "پښتو · Pashto",
            englishName = "Pashto",
            script = ScriptId.ARABIC,
            localeTag = "ps-AF",
            layoutIds = listOf(AssetLayouts.PS_PASHTO_ID),
            numeralSystem = NumeralSystem.PERSIAN,
        ),
        LanguageDef(
            id = "sd",
            displayName = "سنڌي · Sindhi",
            englishName = "Sindhi",
            script = ScriptId.ARABIC,
            localeTag = "sd-PK",
            layoutIds = listOf(AssetLayouts.SD_SINDHI_ID),
            numeralSystem = NumeralSystem.PERSIAN,
        ),
        LanguageDef(
            id = "ug",
            displayName = "ئۇيغۇرچە · Uyghur",
            englishName = "Uyghur",
            script = ScriptId.ARABIC,
            localeTag = "ug-CN",
            layoutIds = listOf(AssetLayouts.UG_UYGHUR_ID),
            numeralSystem = NumeralSystem.ARABIC_INDIC,
        ),
        LanguageDef(
            id = "ckb",
            displayName = "کوردی · Kurdish (Sorani)",
            englishName = "Kurdish (Sorani)",
            script = ScriptId.ARABIC,
            localeTag = "ckb-IQ",
            layoutIds = listOf(AssetLayouts.CKB_SORANI_ID),
            numeralSystem = NumeralSystem.PERSIAN,
        ),
        LanguageDef(
            id = "hy",
            displayName = "Հայերեն · Armenian",
            englishName = "Armenian",
            script = ScriptId.ARMENIAN,
            localeTag = "hy-AM",
            layoutIds = listOf(AssetLayouts.HY_PHONETIC_ID, AssetLayouts.HY_EASTERN_ID),
        ),
        LanguageDef(
            id = "mk",
            displayName = "Македонски · Macedonian",
            englishName = "Macedonian",
            script = ScriptId.CYRILLIC,
            localeTag = "mk-MK",
            layoutIds = listOf(AssetLayouts.MK_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "kk",
            displayName = "Қазақша · Kazakh",
            englishName = "Kazakh",
            script = ScriptId.CYRILLIC,
            localeTag = "kk-KZ",
            layoutIds = listOf(AssetLayouts.KK_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "ky",
            displayName = "Кыргызча · Kyrgyz",
            englishName = "Kyrgyz",
            script = ScriptId.CYRILLIC,
            localeTag = "ky-KG",
            layoutIds = listOf(AssetLayouts.KY_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "tg",
            displayName = "Тоҷикӣ · Tajik",
            englishName = "Tajik",
            script = ScriptId.CYRILLIC,
            localeTag = "tg-TJ",
            layoutIds = listOf(AssetLayouts.TG_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "mn",
            displayName = "Монгол · Mongolian",
            englishName = "Mongolian",
            script = ScriptId.CYRILLIC,
            localeTag = "mn-MN",
            layoutIds = listOf(AssetLayouts.MN_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "tt",
            displayName = "Татарча · Tatar",
            englishName = "Tatar",
            script = ScriptId.CYRILLIC,
            localeTag = "tt-RU",
            layoutIds = listOf(AssetLayouts.TT_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "ba",
            displayName = "Башҡортса · Bashkir",
            englishName = "Bashkir",
            script = ScriptId.CYRILLIC,
            localeTag = "ba-RU",
            layoutIds = listOf(AssetLayouts.BA_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "cv",
            displayName = "Чӑвашла · Chuvash",
            englishName = "Chuvash",
            script = ScriptId.CYRILLIC,
            localeTag = "cv-RU",
            layoutIds = listOf(AssetLayouts.CV_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "ce",
            displayName = "Нохчийн · Chechen",
            englishName = "Chechen",
            script = ScriptId.CYRILLIC,
            localeTag = "ce-RU",
            layoutIds = listOf(AssetLayouts.CE_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "os",
            displayName = "Ирон · Ossetian",
            englishName = "Ossetian",
            script = ScriptId.CYRILLIC,
            localeTag = "os-RU",
            layoutIds = listOf(AssetLayouts.OS_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "sah",
            displayName = "Саха · Yakut",
            englishName = "Yakut",
            script = ScriptId.CYRILLIC,
            localeTag = "sah-RU",
            layoutIds = listOf(AssetLayouts.SAH_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "mr",
            displayName = "मराठी · Marathi",
            englishName = "Marathi",
            script = ScriptId.DEVANAGARI,
            localeTag = "mr-IN",
            layoutIds = listOf(AssetLayouts.MR_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "ne",
            displayName = "नेपाली · Nepali",
            englishName = "Nepali",
            script = ScriptId.DEVANAGARI,
            localeTag = "ne-NP",
            layoutIds = listOf(AssetLayouts.NE_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "sa",
            displayName = "संस्कृतम् · Sanskrit",
            englishName = "Sanskrit",
            script = ScriptId.DEVANAGARI,
            localeTag = "sa-IN",
            layoutIds = listOf(AssetLayouts.SA_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "ta",
            displayName = "தமிழ் · Tamil",
            englishName = "Tamil",
            script = ScriptId.TAMIL,
            localeTag = "ta-IN",
            layoutIds = listOf(AssetLayouts.TA_TAMIL99_ID),
        ),
        LanguageDef(
            id = "si",
            displayName = "සිංහල · Sinhala",
            englishName = "Sinhala",
            script = ScriptId.SINHALA,
            localeTag = "si-LK",
            layoutIds = listOf(AssetLayouts.SI_WIJESEKARA_ID),
        ),
        LanguageDef(
            id = "te",
            displayName = "తెలుగు · Telugu",
            englishName = "Telugu",
            script = ScriptId.TELUGU,
            localeTag = "te-IN",
            layoutIds = listOf(AssetLayouts.TE_INSCRIPT_ID),
        ),
        LanguageDef(
            id = "kn",
            displayName = "ಕನ್ನಡ · Kannada",
            englishName = "Kannada",
            script = ScriptId.KANNADA,
            localeTag = "kn-IN",
            layoutIds = listOf(AssetLayouts.KN_INSCRIPT_ID),
        ),
        LanguageDef(
            id = "ml",
            displayName = "മലയാളം · Malayalam",
            englishName = "Malayalam",
            script = ScriptId.MALAYALAM,
            localeTag = "ml-IN",
            layoutIds = listOf(AssetLayouts.ML_INSCRIPT_ID),
        ),
        LanguageDef(
            id = "gu",
            displayName = "ગુજરાતી · Gujarati",
            englishName = "Gujarati",
            script = ScriptId.GUJARATI,
            localeTag = "gu-IN",
            layoutIds = listOf(AssetLayouts.GU_INSCRIPT_ID),
        ),
        LanguageDef(
            id = "pa",
            displayName = "ਪੰਜਾਬੀ · Punjabi",
            englishName = "Punjabi",
            script = ScriptId.GURMUKHI,
            localeTag = "pa-IN",
            layoutIds = listOf(AssetLayouts.PA_INSCRIPT_ID),
        ),
        LanguageDef(
            id = "or",
            displayName = "ଓଡ଼ିଆ · Odia",
            englishName = "Odia",
            script = ScriptId.ORIYA,
            localeTag = "or-IN",
            layoutIds = listOf(AssetLayouts.OR_INSCRIPT_ID),
        ),
        LanguageDef(
            id = "ca",
            displayName = "Català · Catalan",
            englishName = "Catalan",
            script = ScriptId.LATIN,
            localeTag = "ca-ES",
            layoutIds = listOf(AssetLayouts.CA_CATALAN_ID),
        ),
        LanguageDef(
            id = "gl",
            displayName = "Galego · Galician",
            englishName = "Galician",
            script = ScriptId.LATIN,
            localeTag = "gl-ES",
            layoutIds = listOf(AssetLayouts.GL_GALICIAN_ID),
        ),
        LanguageDef(
            id = "eu",
            displayName = "Euskara · Basque",
            englishName = "Basque",
            script = ScriptId.LATIN,
            localeTag = "eu-ES",
            layoutIds = listOf(AssetLayouts.EU_BASQUE_ID),
        ),
        LanguageDef(
            id = "oc",
            displayName = "Occitan · Occitan",
            englishName = "Occitan",
            script = ScriptId.LATIN,
            localeTag = "oc-FR",
            layoutIds = listOf(AssetLayouts.OC_OCCITAN_ID),
        ),
        LanguageDef(
            id = "br",
            displayName = "Brezhoneg · Breton",
            englishName = "Breton",
            script = ScriptId.LATIN,
            localeTag = "br-FR",
            layoutIds = listOf(AssetLayouts.BR_BRETON_ID),
        ),
        LanguageDef(
            id = "co",
            displayName = "Corsu · Corsican",
            englishName = "Corsican",
            script = ScriptId.LATIN,
            localeTag = "co-FR",
            layoutIds = listOf(AssetLayouts.CO_CORSICAN_ID),
        ),
        LanguageDef(
            id = "la",
            displayName = "Latina · Latin",
            englishName = "Latin",
            script = ScriptId.LATIN,
            localeTag = "la",
            layoutIds = listOf(AssetLayouts.LA_LATIN_ID),
        ),
        LanguageDef(
            id = "lb",
            displayName = "Lëtzebuergesch · Luxembourgish",
            englishName = "Luxembourgish",
            script = ScriptId.LATIN,
            localeTag = "lb-LU",
            layoutIds = listOf(AssetLayouts.LB_LUXEMBOURGISH_ID),
        ),
        LanguageDef(
            id = "fy",
            displayName = "Frysk · Frisian",
            englishName = "Western Frisian",
            script = ScriptId.LATIN,
            localeTag = "fy-NL",
            layoutIds = listOf(AssetLayouts.FY_FRISIAN_ID),
        ),
        LanguageDef(
            id = "fo",
            displayName = "Føroyskt · Faroese",
            englishName = "Faroese",
            script = ScriptId.LATIN,
            localeTag = "fo-FO",
            layoutIds = listOf(AssetLayouts.FO_FAROESE_ID),
        ),
        LanguageDef(
            id = "cy",
            displayName = "Cymraeg · Welsh",
            englishName = "Welsh",
            script = ScriptId.LATIN,
            localeTag = "cy-GB",
            layoutIds = listOf(AssetLayouts.CY_WELSH_ID),
        ),
        LanguageDef(
            id = "ga",
            displayName = "Gaeilge · Irish",
            englishName = "Irish",
            script = ScriptId.LATIN,
            localeTag = "ga-IE",
            layoutIds = listOf(AssetLayouts.GA_IRISH_ID),
        ),
        LanguageDef(
            id = "gd",
            displayName = "Gàidhlig · Scottish Gaelic",
            englishName = "Scottish Gaelic",
            script = ScriptId.LATIN,
            localeTag = "gd-GB",
            layoutIds = listOf(AssetLayouts.GD_GAELIC_ID),
        ),
        LanguageDef(
            id = "is",
            displayName = "Íslenska · Icelandic",
            englishName = "Icelandic",
            script = ScriptId.LATIN,
            localeTag = "is-IS",
            layoutIds = listOf(AssetLayouts.IS_ICELANDIC_ID),
        ),
        LanguageDef(
            id = "sq",
            displayName = "Shqip · Albanian",
            englishName = "Albanian",
            script = ScriptId.LATIN,
            localeTag = "sq-AL",
            layoutIds = listOf(AssetLayouts.SQ_ALBANIAN_ID),
        ),
        LanguageDef(
            id = "mt",
            displayName = "Malti · Maltese",
            englishName = "Maltese",
            script = ScriptId.LATIN,
            localeTag = "mt-MT",
            layoutIds = listOf(AssetLayouts.MT_MALTESE_ID),
        ),
        LanguageDef(
            id = "eo",
            displayName = "Esperanto · Esperanto",
            englishName = "Esperanto",
            script = ScriptId.LATIN,
            localeTag = "eo",
            layoutIds = listOf(AssetLayouts.EO_ESPERANTO_ID),
        ),
        LanguageDef(
            id = "af",
            displayName = "Afrikaans · Afrikaans",
            englishName = "Afrikaans",
            script = ScriptId.LATIN,
            localeTag = "af-ZA",
            layoutIds = listOf(AssetLayouts.AF_AFRIKAANS_ID),
        ),
        LanguageDef(
            id = "tr",
            displayName = "Türkçe · Turkish",
            englishName = "Turkish",
            script = ScriptId.LATIN,
            localeTag = "tr-TR",
            layoutIds = listOf(AssetLayouts.TR_TURKISH_Q_ID),
        ),
        LanguageDef(
            id = "az",
            displayName = "Azərbaycan · Azerbaijani",
            englishName = "Azerbaijani",
            script = ScriptId.LATIN,
            localeTag = "az-AZ",
            layoutIds = listOf(AssetLayouts.AZ_LATIN_ID),
        ),
        LanguageDef(
            id = "uz",
            displayName = "Oʻzbek · Uzbek",
            englishName = "Uzbek",
            script = ScriptId.LATIN,
            localeTag = "uz-UZ",
            layoutIds = listOf(AssetLayouts.UZ_LATIN_ID),
        ),
        LanguageDef(
            id = "tk",
            displayName = "Türkmen · Turkmen",
            englishName = "Turkmen",
            script = ScriptId.LATIN,
            localeTag = "tk-TM",
            layoutIds = listOf(AssetLayouts.TK_LATIN_ID),
        ),
        LanguageDef(
            id = "ku",
            displayName = "Kurdî · Kurdish",
            englishName = "Kurdish",
            script = ScriptId.LATIN,
            localeTag = "ku-TR",
            layoutIds = listOf(AssetLayouts.KU_KURMANJI_ID),
        ),
        LanguageDef(
            id = "id",
            displayName = "Indonesia · Indonesian",
            englishName = "Indonesian",
            script = ScriptId.LATIN,
            localeTag = "id-ID",
            layoutIds = listOf(AssetLayouts.ID_QWERTY_ID),
        ),
        LanguageDef(
            id = "ms",
            displayName = "Melayu · Malay",
            englishName = "Malay",
            script = ScriptId.LATIN,
            localeTag = "ms-MY",
            layoutIds = listOf(AssetLayouts.MS_QWERTY_ID),
        ),
        LanguageDef(
            id = "tl",
            displayName = "Filipino · Filipino",
            englishName = "Filipino",
            script = ScriptId.LATIN,
            localeTag = "tl-PH",
            layoutIds = listOf(AssetLayouts.TL_QWERTY_ID),
        ),
        LanguageDef(
            id = "ceb",
            displayName = "Cebuano · Cebuano",
            englishName = "Cebuano",
            script = ScriptId.LATIN,
            localeTag = "ceb-PH",
            layoutIds = listOf(AssetLayouts.CEB_QWERTY_ID),
        ),
        LanguageDef(
            id = "jv",
            displayName = "Basa Jawa · Javanese",
            englishName = "Javanese",
            script = ScriptId.LATIN,
            localeTag = "jv-ID",
            layoutIds = listOf(AssetLayouts.JV_QWERTY_ID),
        ),
        LanguageDef(
            id = "su",
            displayName = "Basa Sunda · Sundanese",
            englishName = "Sundanese",
            script = ScriptId.LATIN,
            localeTag = "su-ID",
            layoutIds = listOf(AssetLayouts.SU_QWERTY_ID),
        ),
        LanguageDef(
            id = "mi",
            displayName = "Māori · Maori",
            englishName = "Maori",
            script = ScriptId.LATIN,
            localeTag = "mi-NZ",
            layoutIds = listOf(AssetLayouts.MI_QWERTY_ID),
        ),
        LanguageDef(
            id = "haw",
            displayName = "ʻŌlelo Hawaiʻi · Hawaiian",
            englishName = "Hawaiian",
            script = ScriptId.LATIN,
            localeTag = "haw-US",
            layoutIds = listOf(AssetLayouts.HAW_QWERTY_ID),
        ),
        LanguageDef(
            id = "mg",
            displayName = "Malagasy · Malagasy",
            englishName = "Malagasy",
            script = ScriptId.LATIN,
            localeTag = "mg-MG",
            layoutIds = listOf(AssetLayouts.MG_QWERTY_ID),
        ),
        LanguageDef(
            id = "sm",
            displayName = "Gagana Sāmoa · Samoan",
            englishName = "Samoan",
            script = ScriptId.LATIN,
            localeTag = "sm-WS",
            layoutIds = listOf(AssetLayouts.SM_QWERTY_ID),
        ),
        LanguageDef(
            id = "fj",
            displayName = "Vosa Vakaviti · Fijian",
            englishName = "Fijian",
            script = ScriptId.LATIN,
            localeTag = "fj-FJ",
            layoutIds = listOf(AssetLayouts.FJ_QWERTY_ID),
        ),
        LanguageDef(
            id = "to",
            displayName = "lea faka-Tonga · Tongan",
            englishName = "Tongan",
            script = ScriptId.LATIN,
            localeTag = "to-TO",
            layoutIds = listOf(AssetLayouts.TO_QWERTY_ID),
        ),
        LanguageDef(
            id = "sw",
            displayName = "Kiswahili · Swahili",
            englishName = "Swahili",
            script = ScriptId.LATIN,
            localeTag = "sw-KE",
            layoutIds = listOf(AssetLayouts.SW_QWERTY_ID),
        ),
        LanguageDef(
            id = "zu",
            displayName = "isiZulu · Zulu",
            englishName = "Zulu",
            script = ScriptId.LATIN,
            localeTag = "zu-ZA",
            layoutIds = listOf(AssetLayouts.ZU_QWERTY_ID),
        ),
        LanguageDef(
            id = "xh",
            displayName = "isiXhosa · Xhosa",
            englishName = "Xhosa",
            script = ScriptId.LATIN,
            localeTag = "xh-ZA",
            layoutIds = listOf(AssetLayouts.XH_QWERTY_ID),
        ),
        LanguageDef(
            id = "yo",
            displayName = "Yorùbá · Yoruba",
            englishName = "Yoruba",
            script = ScriptId.LATIN,
            localeTag = "yo-NG",
            layoutIds = listOf(AssetLayouts.YO_QWERTY_ID),
        ),
        LanguageDef(
            id = "ig",
            displayName = "Igbo · Igbo",
            englishName = "Igbo",
            script = ScriptId.LATIN,
            localeTag = "ig-NG",
            layoutIds = listOf(AssetLayouts.IG_QWERTY_ID),
        ),
        LanguageDef(
            id = "ha",
            displayName = "Hausa · Hausa",
            englishName = "Hausa",
            script = ScriptId.LATIN,
            localeTag = "ha-NG",
            layoutIds = listOf(AssetLayouts.HA_QWERTY_ID),
        ),
        LanguageDef(
            id = "so",
            displayName = "Soomaali · Somali",
            englishName = "Somali",
            script = ScriptId.LATIN,
            localeTag = "so-SO",
            layoutIds = listOf(AssetLayouts.SO_QWERTY_ID),
        ),
        LanguageDef(
            id = "rw",
            displayName = "Kinyarwanda · Kinyarwanda",
            englishName = "Kinyarwanda",
            script = ScriptId.LATIN,
            localeTag = "rw-RW",
            layoutIds = listOf(AssetLayouts.RW_QWERTY_ID),
        ),
        LanguageDef(
            id = "ln",
            displayName = "Lingála · Lingala",
            englishName = "Lingala",
            script = ScriptId.LATIN,
            localeTag = "ln-CD",
            layoutIds = listOf(AssetLayouts.LN_QWERTY_ID),
        ),
        LanguageDef(
            id = "ny",
            displayName = "Chichewa · Chichewa",
            englishName = "Chichewa",
            script = ScriptId.LATIN,
            localeTag = "ny-MW",
            layoutIds = listOf(AssetLayouts.NY_QWERTY_ID),
        ),
        LanguageDef(
            id = "sn",
            displayName = "chiShona · Shona",
            englishName = "Shona",
            script = ScriptId.LATIN,
            localeTag = "sn-ZW",
            layoutIds = listOf(AssetLayouts.SN_QWERTY_ID),
        ),
        LanguageDef(
            id = "st",
            displayName = "Sesotho · Sesotho",
            englishName = "Sesotho",
            script = ScriptId.LATIN,
            localeTag = "st-LS",
            layoutIds = listOf(AssetLayouts.ST_QWERTY_ID),
        ),
        LanguageDef(
            id = "tn",
            displayName = "Setswana · Tswana",
            englishName = "Tswana",
            script = ScriptId.LATIN,
            localeTag = "tn-BW",
            layoutIds = listOf(AssetLayouts.TN_QWERTY_ID),
        ),
        LanguageDef(
            id = "wo",
            displayName = "Wolof · Wolof",
            englishName = "Wolof",
            script = ScriptId.LATIN,
            localeTag = "wo-SN",
            layoutIds = listOf(AssetLayouts.WO_QWERTY_ID),
        ),
        LanguageDef(
            id = "vi",
            displayName = "Tiếng Việt · Vietnamese",
            englishName = "Vietnamese",
            script = ScriptId.LATIN,
            localeTag = "vi-VN",
            layoutIds = listOf(
                AssetLayouts.VI_TELEX_ID,
                AssetLayouts.VI_VNI_ID,
                AssetLayouts.VI_QWERTY_ID,
            ),
        ),
        // CJK conversion IMEs. The script default is a plain append; the layout's
        // composer (romaji→kana, pinyin) drives the input, with candidates in the
        // strip. Neither ships a word list — the bundled conversion tables are what
        // turn a reading into characters.
        LanguageDef(
            id = "ja",
            displayName = "日本語 · Japanese",
            englishName = "Japanese",
            script = ScriptId.JAPANESE,
            localeTag = "ja-JP",
            layoutIds = listOf(
                AssetLayouts.JA_ROMAJI_ID,
                AssetLayouts.JA_FLICK_ID,
                AssetLayouts.JA_KANA_JIS_ID,
            ),
        ),
        LanguageDef(
            id = "zh",
            displayName = "中文 · Chinese",
            englishName = "Chinese",
            script = ScriptId.HAN,
            localeTag = "zh-CN",
            layoutIds = listOf(
                AssetLayouts.ZH_PINYIN_ID,
                AssetLayouts.ZH_PINYIN_T9_ID,
                AssetLayouts.ZH_ZHUYIN_ID,
                AssetLayouts.ZH_STROKE_ID,
            ),
        ),
        LanguageDef(
            id = "ht",
            displayName = "Kreyòl · Haitian Creole",
            englishName = "Haitian Creole",
            script = ScriptId.LATIN,
            localeTag = "ht-HT",
            layoutIds = listOf(AssetLayouts.HT_QWERTY_ID),
        ),
        LanguageDef(
            id = "qu",
            displayName = "Runa Simi · Quechua",
            englishName = "Quechua",
            script = ScriptId.LATIN,
            localeTag = "qu-PE",
            layoutIds = listOf(AssetLayouts.QU_QWERTY_ID),
        ),
        LanguageDef(
            id = "gn",
            displayName = "Avañeʼẽ · Guarani",
            englishName = "Guarani",
            script = ScriptId.LATIN,
            localeTag = "gn-PY",
            layoutIds = listOf(AssetLayouts.GN_QWERTY_ID),
        ),
        LanguageDef(
            id = "th",
            displayName = "ไทย · Thai",
            englishName = "Thai",
            script = ScriptId.THAI,
            localeTag = "th-TH",
            layoutIds = listOf(AssetLayouts.TH_KEDMANEE_ID),
        ),
        LanguageDef(
            id = "lo",
            displayName = "ລາວ · Lao",
            englishName = "Lao",
            script = ScriptId.LAO,
            localeTag = "lo-LA",
            layoutIds = listOf(AssetLayouts.LO_LAO_ID),
        ),
        LanguageDef(
            id = "km",
            displayName = "ខ្មែរ · Khmer",
            englishName = "Khmer",
            script = ScriptId.KHMER,
            localeTag = "km-KH",
            layoutIds = listOf(AssetLayouts.KM_NIDA_ID),
        ),
        LanguageDef(
            id = "my",
            displayName = "မြန်မာ · Burmese",
            englishName = "Burmese",
            script = ScriptId.MYANMAR,
            localeTag = "my-MM",
            layoutIds = listOf(AssetLayouts.MY_MYANMAR3_ID),
        ),
        LanguageDef(
            id = "udm",
            displayName = "Удмурт · Udmurt",
            englishName = "Udmurt",
            script = ScriptId.CYRILLIC,
            localeTag = "udm-RU",
            layoutIds = listOf(AssetLayouts.UDM_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "kv",
            displayName = "Коми · Komi",
            englishName = "Komi",
            script = ScriptId.CYRILLIC,
            localeTag = "kv-RU",
            layoutIds = listOf(AssetLayouts.KV_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "xal",
            displayName = "Хальмг · Kalmyk",
            englishName = "Kalmyk",
            script = ScriptId.CYRILLIC,
            localeTag = "xal-RU",
            layoutIds = listOf(AssetLayouts.XAL_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "tyv",
            displayName = "Тыва · Tuvan",
            englishName = "Tuvan",
            script = ScriptId.CYRILLIC,
            localeTag = "tyv-RU",
            layoutIds = listOf(AssetLayouts.TYV_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "bua",
            displayName = "Буряад · Buryat",
            englishName = "Buryat",
            script = ScriptId.CYRILLIC,
            localeTag = "bua-RU",
            layoutIds = listOf(AssetLayouts.BUA_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "myv",
            displayName = "Эрзянь · Erzya",
            englishName = "Erzya",
            script = ScriptId.CYRILLIC,
            localeTag = "myv-RU",
            layoutIds = listOf(AssetLayouts.MYV_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "chm",
            displayName = "Марий · Mari",
            englishName = "Mari",
            script = ScriptId.CYRILLIC,
            localeTag = "chm-RU",
            layoutIds = listOf(AssetLayouts.CHM_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "ady",
            displayName = "Адыгабзэ · Adyghe",
            englishName = "Adyghe",
            script = ScriptId.CYRILLIC,
            localeTag = "ady-RU",
            layoutIds = listOf(AssetLayouts.ADY_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "kbd",
            displayName = "Адыгэбзэ · Kabardian",
            englishName = "Kabardian",
            script = ScriptId.CYRILLIC,
            localeTag = "kbd-RU",
            layoutIds = listOf(AssetLayouts.KBD_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "ab",
            displayName = "Аҧсуа · Abkhaz",
            englishName = "Abkhaz",
            script = ScriptId.CYRILLIC,
            localeTag = "ab-GE",
            layoutIds = listOf(AssetLayouts.AB_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "av",
            displayName = "Магӏарул · Avar",
            englishName = "Avar",
            script = ScriptId.CYRILLIC,
            localeTag = "av-RU",
            layoutIds = listOf(AssetLayouts.AV_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "lez",
            displayName = "Лезги · Lezgian",
            englishName = "Lezgian",
            script = ScriptId.CYRILLIC,
            localeTag = "lez-RU",
            layoutIds = listOf(AssetLayouts.LEZ_CYRILLIC_ID),
        ),
        LanguageDef(
            id = "kok",
            displayName = "कोंकणी · Konkani",
            englishName = "Konkani",
            script = ScriptId.DEVANAGARI,
            localeTag = "kok-IN",
            layoutIds = listOf(AssetLayouts.KOK_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "mai",
            displayName = "मैथिली · Maithili",
            englishName = "Maithili",
            script = ScriptId.DEVANAGARI,
            localeTag = "mai-IN",
            layoutIds = listOf(AssetLayouts.MAI_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "brx",
            displayName = "बड़ो · Bodo",
            englishName = "Bodo",
            script = ScriptId.DEVANAGARI,
            localeTag = "brx-IN",
            layoutIds = listOf(AssetLayouts.BRX_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "doi",
            displayName = "डोगरी · Dogri",
            englishName = "Dogri",
            script = ScriptId.DEVANAGARI,
            localeTag = "doi-IN",
            layoutIds = listOf(AssetLayouts.DOI_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "bho",
            displayName = "भोजपुरी · Bhojpuri",
            englishName = "Bhojpuri",
            script = ScriptId.DEVANAGARI,
            localeTag = "bho-IN",
            layoutIds = listOf(AssetLayouts.BHO_INSCRIPT_ID),
            numeralSystem = NumeralSystem.DEVANAGARI,
        ),
        LanguageDef(
            id = "am",
            displayName = "አማርኛ · Amharic",
            englishName = "Amharic",
            script = ScriptId.ETHIOPIC,
            localeTag = "am-ET",
            layoutIds = listOf(AssetLayouts.AM_ETHIOPIC_ID),
        ),
        LanguageDef(
            id = "ti",
            displayName = "ትግርኛ · Tigrinya",
            englishName = "Tigrinya",
            script = ScriptId.ETHIOPIC,
            localeTag = "ti-ET",
            layoutIds = listOf(AssetLayouts.TI_ETHIOPIC_ID),
        ),
        LanguageDef(
            id = "rm",
            displayName = "Rumantsch · Romansh",
            englishName = "Romansh",
            script = ScriptId.LATIN,
            localeTag = "rm-CH",
            layoutIds = listOf(AssetLayouts.RM_QWERTY_ID),
        ),
        LanguageDef(
            id = "wa",
            displayName = "Walon · Walloon",
            englishName = "Walloon",
            script = ScriptId.LATIN,
            localeTag = "wa-BE",
            layoutIds = listOf(AssetLayouts.WA_QWERTY_ID),
        ),
        LanguageDef(
            id = "scn",
            displayName = "Sicilianu · Sicilian",
            englishName = "Sicilian",
            script = ScriptId.LATIN,
            localeTag = "scn-IT",
            layoutIds = listOf(AssetLayouts.SCN_QWERTY_ID),
        ),
        LanguageDef(
            id = "vec",
            displayName = "Vèneto · Venetian",
            englishName = "Venetian",
            script = ScriptId.LATIN,
            localeTag = "vec-IT",
            layoutIds = listOf(AssetLayouts.VEC_QWERTY_ID),
        ),
        LanguageDef(
            id = "lij",
            displayName = "Ligure · Ligurian",
            englishName = "Ligurian",
            script = ScriptId.LATIN,
            localeTag = "lij-IT",
            layoutIds = listOf(AssetLayouts.LIJ_QWERTY_ID),
        ),
        LanguageDef(
            id = "nap",
            displayName = "Napulitano · Neapolitan",
            englishName = "Neapolitan",
            script = ScriptId.LATIN,
            localeTag = "nap-IT",
            layoutIds = listOf(AssetLayouts.NAP_QWERTY_ID),
        ),
        LanguageDef(
            id = "fur",
            displayName = "Furlan · Friulian",
            englishName = "Friulian",
            script = ScriptId.LATIN,
            localeTag = "fur-IT",
            layoutIds = listOf(AssetLayouts.FUR_QWERTY_ID),
        ),
        LanguageDef(
            id = "csb",
            displayName = "Kaszëbsczi · Kashubian",
            englishName = "Kashubian",
            script = ScriptId.LATIN,
            localeTag = "csb-PL",
            layoutIds = listOf(AssetLayouts.CSB_QWERTY_ID),
        ),
        LanguageDef(
            id = "hsb",
            displayName = "Hornjoserbsce · Upper Sorbian",
            englishName = "Upper Sorbian",
            script = ScriptId.LATIN,
            localeTag = "hsb-DE",
            layoutIds = listOf(AssetLayouts.HSB_QWERTZ_ID),
        ),
        LanguageDef(
            id = "dsb",
            displayName = "Dolnoserbski · Lower Sorbian",
            englishName = "Lower Sorbian",
            script = ScriptId.LATIN,
            localeTag = "dsb-DE",
            layoutIds = listOf(AssetLayouts.DSB_QWERTZ_ID),
        ),
        LanguageDef(
            id = "gv",
            displayName = "Gaelg · Manx",
            englishName = "Manx",
            script = ScriptId.LATIN,
            localeTag = "gv-IM",
            layoutIds = listOf(AssetLayouts.GV_QWERTY_ID),
        ),
        LanguageDef(
            id = "kw",
            displayName = "Kernewek · Cornish",
            englishName = "Cornish",
            script = ScriptId.LATIN,
            localeTag = "kw-GB",
            layoutIds = listOf(AssetLayouts.KW_QWERTY_ID),
        ),
        LanguageDef(
            id = "rup",
            displayName = "Armãneashti · Aromanian",
            englishName = "Aromanian",
            script = ScriptId.LATIN,
            localeTag = "rup",
            layoutIds = listOf(AssetLayouts.RUP_QWERTY_ID),
        ),
        LanguageDef(
            id = "crh",
            displayName = "Qırımtatar · Crimean Tatar",
            englishName = "Crimean Tatar",
            script = ScriptId.LATIN,
            localeTag = "crh-Latn",
            layoutIds = listOf(AssetLayouts.CRH_QWERTY_ID),
        ),
        LanguageDef(
            id = "om",
            displayName = "Afaan Oromoo · Oromo",
            englishName = "Oromo",
            script = ScriptId.LATIN,
            localeTag = "om-ET",
            layoutIds = listOf(AssetLayouts.OM_QWERTY_ID),
        ),
        LanguageDef(
            id = "nso",
            displayName = "Sesotho sa Leboa · Northern Sotho",
            englishName = "Northern Sotho",
            script = ScriptId.LATIN,
            localeTag = "nso-ZA",
            layoutIds = listOf(AssetLayouts.NSO_QWERTY_ID),
        ),
        LanguageDef(
            id = "ts",
            displayName = "Xitsonga · Tsonga",
            englishName = "Tsonga",
            script = ScriptId.LATIN,
            localeTag = "ts-ZA",
            layoutIds = listOf(AssetLayouts.TS_QWERTY_ID),
        ),
        LanguageDef(
            id = "ve",
            displayName = "Tshivenḓa · Venda",
            englishName = "Venda",
            script = ScriptId.LATIN,
            localeTag = "ve-ZA",
            layoutIds = listOf(AssetLayouts.VE_QWERTY_ID),
        ),
        LanguageDef(
            id = "ss",
            displayName = "siSwati · Swati",
            englishName = "Swati",
            script = ScriptId.LATIN,
            localeTag = "ss-SZ",
            layoutIds = listOf(AssetLayouts.SS_QWERTY_ID),
        ),
        LanguageDef(
            id = "nd",
            displayName = "isiNdebele · Ndebele",
            englishName = "Ndebele",
            script = ScriptId.LATIN,
            localeTag = "nd-ZW",
            layoutIds = listOf(AssetLayouts.ND_QWERTY_ID),
        ),
        LanguageDef(
            id = "lg",
            displayName = "Luganda · Ganda",
            englishName = "Ganda",
            script = ScriptId.LATIN,
            localeTag = "lg-UG",
            layoutIds = listOf(AssetLayouts.LG_QWERTY_ID),
        ),
        LanguageDef(
            id = "ki",
            displayName = "Gĩkũyũ · Kikuyu",
            englishName = "Kikuyu",
            script = ScriptId.LATIN,
            localeTag = "ki-KE",
            layoutIds = listOf(AssetLayouts.KI_QWERTY_ID),
        ),
        LanguageDef(
            id = "ak",
            displayName = "Akan · Akan",
            englishName = "Akan",
            script = ScriptId.LATIN,
            localeTag = "ak-GH",
            layoutIds = listOf(AssetLayouts.AK_QWERTY_ID),
        ),
        LanguageDef(
            id = "ee",
            displayName = "Eʋegbe · Ewe",
            englishName = "Ewe",
            script = ScriptId.LATIN,
            localeTag = "ee-GH",
            layoutIds = listOf(AssetLayouts.EE_QWERTY_ID),
        ),
        LanguageDef(
            id = "bm",
            displayName = "Bamanankan · Bambara",
            englishName = "Bambara",
            script = ScriptId.LATIN,
            localeTag = "bm-ML",
            layoutIds = listOf(AssetLayouts.BM_QWERTY_ID),
        ),
        LanguageDef(
            id = "ay",
            displayName = "Aymar aru · Aymara",
            englishName = "Aymara",
            script = ScriptId.LATIN,
            localeTag = "ay-BO",
            layoutIds = listOf(AssetLayouts.AY_QWERTY_ID),
        ),
        LanguageDef(
            id = "ty",
            displayName = "Reo Tahiti · Tahitian",
            englishName = "Tahitian",
            script = ScriptId.LATIN,
            localeTag = "ty-PF",
            layoutIds = listOf(AssetLayouts.TY_QWERTY_ID),
        ),
        LanguageDef(
            id = "bi",
            displayName = "Bislama · Bislama",
            englishName = "Bislama",
            script = ScriptId.LATIN,
            localeTag = "bi-VU",
            layoutIds = listOf(AssetLayouts.BI_QWERTY_ID),
        ),
        LanguageDef(
            id = "tet",
            displayName = "Tetun · Tetum",
            englishName = "Tetum",
            script = ScriptId.LATIN,
            localeTag = "tet-TL",
            layoutIds = listOf(AssetLayouts.TET_QWERTY_ID),
        ),
        LanguageDef(
            id = "ia",
            displayName = "Interlingua · Interlingua",
            englishName = "Interlingua",
            script = ScriptId.LATIN,
            localeTag = "ia",
            layoutIds = listOf(AssetLayouts.IA_QWERTY_ID),
        ),
        LanguageDef(
            id = "dv",
            displayName = "ދިވެހި · Dhivehi",
            englishName = "Dhivehi",
            script = ScriptId.THAANA,
            localeTag = "dv-MV",
            layoutIds = listOf(AssetLayouts.DV_THAANA_ID),
        ),
        LanguageDef(
            id = "jbo",
            displayName = "la .lojban. · Lojban",
            englishName = "Lojban",
            script = ScriptId.LATIN,
            localeTag = "jbo",
            layoutIds = listOf(BuiltInLayouts.QWERTY_ID),
        ),
        LanguageDef(
            id = "tlh",
            displayName = "tlhIngan Hol · Klingon",
            englishName = "Klingon",
            script = ScriptId.LATIN,
            localeTag = "tlh",
            layoutIds = listOf(BuiltInLayouts.QWERTY_ID),
        ),
        LanguageDef(
            id = "se",
            displayName = "Sámegiella · Northern Sami",
            englishName = "Northern Sami",
            script = ScriptId.LATIN,
            localeTag = "se-NO",
            layoutIds = listOf(AssetLayouts.SE_QWERTY_ID),
        ),
        LanguageDef(
            id = "smn",
            displayName = "Anarâškielâ · Inari Sami",
            englishName = "Inari Sami",
            script = ScriptId.LATIN,
            localeTag = "smn-FI",
            layoutIds = listOf(AssetLayouts.SMN_QWERTY_ID),
        ),
        LanguageDef(
            id = "sms",
            displayName = "Sääʹmkiõll · Skolt Sami",
            englishName = "Skolt Sami",
            script = ScriptId.LATIN,
            localeTag = "sms-FI",
            layoutIds = listOf(AssetLayouts.SMS_QWERTY_ID),
        ),
        LanguageDef(
            id = "sc",
            displayName = "Sardu · Sardinian",
            englishName = "Sardinian",
            script = ScriptId.LATIN,
            localeTag = "sc-IT",
            layoutIds = listOf(AssetLayouts.SC_QWERTY_ID),
        ),
        LanguageDef(
            id = "pms",
            displayName = "Piemontèis · Piedmontese",
            englishName = "Piedmontese",
            script = ScriptId.LATIN,
            localeTag = "pms-IT",
            layoutIds = listOf(AssetLayouts.PMS_QWERTY_ID),
        ),
        LanguageDef(
            id = "lld",
            displayName = "Ladin · Ladin",
            englishName = "Ladin",
            script = ScriptId.LATIN,
            localeTag = "lld-IT",
            layoutIds = listOf(AssetLayouts.LLD_QWERTY_ID),
        ),
        LanguageDef(
            id = "nrf",
            displayName = "Nourmand · Norman",
            englishName = "Norman",
            script = ScriptId.LATIN,
            localeTag = "nrf-JE",
            layoutIds = listOf(AssetLayouts.NRF_QWERTY_ID),
        ),
        LanguageDef(
            id = "hac",
            displayName = "هَوْرامِی · Hawrami",
            englishName = "Hawrami Kurdish",
            script = ScriptId.ARABIC,
            localeTag = "hac-IQ",
            layoutIds = listOf(AssetLayouts.HAC_STANDARD_ID),
            numeralSystem = NumeralSystem.PERSIAN,
        ),
        LanguageDef(
            id = "yi",
            displayName = "ייִדיש · Yiddish",
            englishName = "Yiddish",
            script = ScriptId.HEBREW,
            localeTag = "yi-001",
            layoutIds = listOf(AssetLayouts.YI_STANDARD_ID),
        ),
        LanguageDef(
            id = "syc",
            displayName = "ܣܘܪܝܝܐ · Syriac",
            englishName = "Syriac",
            script = ScriptId.SYRIAC,
            localeTag = "syc",
            layoutIds = listOf(AssetLayouts.SYC_SYRIAC_ID),
        ),
        LanguageDef(
            id = "grc",
            displayName = "Ancient Greek · Polytonic",
            englishName = "Polytonic Greek",
            script = ScriptId.GREEK,
            localeTag = "grc",
            layoutIds = listOf(AssetLayouts.GRC_POLYTONIC_ID),
        ),
        LanguageDef(
            id = "zgh",
            displayName = "ⵜⴰⵎⴰⵣⵉⵖⵜ · Tamazight",
            englishName = "Tamazight (Tifinagh)",
            script = ScriptId.TIFINAGH,
            localeTag = "zgh-MA",
            layoutIds = listOf(AssetLayouts.ZGH_TIFINAGH_ID),
        ),
        LanguageDef(
            id = "chr",
            displayName = "ᏣᎳᎩ · Cherokee",
            englishName = "Cherokee",
            script = ScriptId.CHEROKEE,
            localeTag = "chr-US",
            layoutIds = listOf(AssetLayouts.CHR_CHEROKEE_ID),
        ),
        LanguageDef(
            id = "nqo",
            displayName = "ߒߞߏ · N’Ko",
            englishName = "N’Ko",
            script = ScriptId.NKO,
            localeTag = "nqo-GN",
            layoutIds = listOf(AssetLayouts.NQO_NKO_ID),
        ),
        LanguageDef(
            id = "iu",
            displayName = "ᐃᓄᒃᑎᑐᑦ · Inuktitut",
            englishName = "Inuktitut",
            script = ScriptId.CANADIAN_ABORIGINAL_SYLLABICS,
            localeTag = "iu-CA",
            layoutIds = listOf(AssetLayouts.IU_SYLLABICS_ID),
        ),
        LanguageDef(
            id = "bo",
            displayName = "བོད་སྐད་ · Tibetan",
            englishName = "Tibetan",
            script = ScriptId.TIBETAN,
            localeTag = "bo-CN",
            layoutIds = listOf(AssetLayouts.BO_TIBETAN_ID),
        ),
        // Not a spoken language but a phonetic notation, offered as one so it rides
        // the same enable/select/layout machinery. "-fonipa" is the BCP-47 variant
        // for IPA transcription; the primary subtag is "mul" (multiple languages)
        // rather than "und", because java.util.Locale maps "und" to an empty
        // language and every locale tag here must parse. No dictionary or gesture
        // lexicon applies.
        LanguageDef(
            id = "ipa",
            displayName = "IPA · Phonetic",
            englishName = "IPA (Phonetic)",
            script = ScriptId.IPA,
            localeTag = "mul-fonipa",
            layoutIds = listOf(AssetLayouts.IPA_ID),
        ),
        // Not a language but a family of styled-Latin "fonts": each layout maps
        // the Latin letters onto a Mathematical-Alphanumeric (or enclosed /
        // fullwidth / combining) variant so a tap commits 𝔣𝔞𝔫𝔠𝔶 𝕦𝕟𝕚𝕔𝕠𝕕𝕖 text
        // straight into any field. It rides the Latin script (bicameral, so shift
        // reaches the capital variant via each key's shiftLabel) and ships no
        // dictionary or gesture lexicon — the substitution is the whole point.
        // Primary subtag "mul" (multiple languages) so the locale tag still parses.
        LanguageDef(
            id = "fancy",
            displayName = "𝓕𝓪𝓷𝓬𝔂 · Fancy Text",
            englishName = "Fancy Text (fonts)",
            script = ScriptId.LATIN,
            localeTag = "mul",
            layoutIds = listOf(
                AssetLayouts.FANCY_BOLD_ID,
                AssetLayouts.FANCY_ITALIC_ID,
                AssetLayouts.FANCY_BOLD_ITALIC_ID,
                AssetLayouts.FANCY_SCRIPT_ID,
                AssetLayouts.FANCY_BOLD_SCRIPT_ID,
                AssetLayouts.FANCY_FRAKTUR_ID,
                AssetLayouts.FANCY_BOLD_FRAKTUR_ID,
                AssetLayouts.FANCY_DOUBLE_STRUCK_ID,
                AssetLayouts.FANCY_SANS_ID,
                AssetLayouts.FANCY_SANS_BOLD_ID,
                AssetLayouts.FANCY_SANS_ITALIC_ID,
                AssetLayouts.FANCY_SANS_BOLD_ITALIC_ID,
                AssetLayouts.FANCY_MONOSPACE_ID,
                AssetLayouts.FANCY_FULLWIDTH_ID,
                AssetLayouts.FANCY_CIRCLED_ID,
                AssetLayouts.FANCY_CIRCLED_FILLED_ID,
                AssetLayouts.FANCY_SQUARED_ID,
                AssetLayouts.FANCY_SQUARED_FILLED_ID,
                AssetLayouts.FANCY_SMALL_CAPS_ID,
                AssetLayouts.FANCY_SUPERSCRIPT_ID,
                AssetLayouts.FANCY_STRIKETHROUGH_ID,
                AssetLayouts.FANCY_UNDERLINE_ID,
            ),
        ),
    )

    /** The stand-in for an id this build does not recognise. Never surfaced in UI. */
    val GENERIC: LanguageDef = LanguageDef(
        id = "und",
        displayName = "Unknown",
        englishName = "Unknown",
        script = ScriptId.LATIN,
        localeTag = "und",
        layoutIds = emptyList(),
    )

    private val index: Map<String, LanguageDef> = all.associateBy { it.id }

    private val byLayout: Map<String, LanguageDef> = buildMap {
        for (lang in all) for (layoutId in lang.layoutIds) putIfAbsent(layoutId, lang)
    }

    fun byId(id: String): LanguageDef = index[id] ?: GENERIC

    /**
     * The language whose primary subtag matches a BCP-47 tag ("fr-FR" → French,
     * "en" → English), for `hintLocales` and OS subtype locales. Null when no
     * offered language matches — the caller decides the fallback.
     */
    fun byLocale(tag: String): LanguageDef? {
        val primary = tag.replace('_', '-').substringBefore('-').lowercase()
        if (primary.isEmpty()) return null
        return all.firstOrNull { it.id == primary || it.localeTag.substringBefore('-').lowercase() == primary }
    }

    /**
     * The language a built-in layout id belongs to. Custom/asset layouts carry
     * their own `langId` on the spec and should resolve through that instead;
     * this covers the built-in ids the UI lists.
     */
    fun languageOf(layoutId: String): LanguageDef = byLayout[layoutId] ?: GENERIC
}
