#!/usr/bin/env python3
"""Regenerate `assets/emoji/animated.txt` from the Noto Animated Emoji index.

Google publishes an animated version of part of the emoji set — around 900 of
them, so a flag or a family sequence usually has none. The keyboard has to know
which ones exist before it offers "send the animated one", because finding out
by asking the server means a 404 round trip per long press.

The index lives at

    https://googlefonts.github.io/noto-emoji-animation/data/api.json

and names each entry by its code points, lowercase hex joined with `_`, which
is exactly the path segment the asset URL takes:

    https://fonts.gstatic.com/s/e/notoemoji/latest/1f600/512.gif

The assets are CC BY 4.0 (see app/src/main/assets/licenses/), so the app credits
Google wherever it offers them.

Usage:
  python3 tools/emoji/generate_animated.py            # network
  python3 tools/emoji/generate_animated.py --check    # verify, don't write
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

INDEX_URL = "https://googlefonts.github.io/noto-emoji-animation/data/api.json"
OUT = Path("app/src/main/assets/emoji/animated.txt")

# Below this the file is not the index — a captive portal, or an API that moved.
MIN_ENTRIES = 500

HEADER = """\
# Code points of every emoji with a Noto Animated Emoji asset, one per line,
# lowercase hex joined with '_' — the path segment of
# https://fonts.gstatic.com/s/e/notoemoji/latest/<code>/512.gif
#
# Animated assets: Noto Animated Emoji, Google, CC BY 4.0.
# Generated by tools/emoji/generate_animated.py. Do not edit by hand.
"""


def fetch_codes() -> list[str]:
    with urllib.request.urlopen(INDEX_URL, timeout=60) as response:
        index = json.load(response)
    codes = sorted({icon["codepoint"] for icon in index.get("icons", [])})
    if len(codes) < MIN_ENTRIES:
        sys.exit(f"only {len(codes)} entries at {INDEX_URL}; refusing to write")
    bad = [code for code in codes if not all(c in "0123456789abcdef_" for c in code)]
    if bad:
        sys.exit(f"unexpected code point spelling: {bad[:5]}")
    return codes


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify, don't write")
    args = parser.parse_args()

    text = HEADER + "\n".join(fetch_codes()) + "\n"
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT} is out of date; run without --check")
        print(f"{OUT} is up to date")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({text.count(chr(10)) - HEADER.count(chr(10))} emoji)")


if __name__ == "__main__":
    main()
