#!/usr/bin/env python3
"""Generate REVIEW.md — every screenshot taken so far, with its context.

Usage:  python3 docs/screenshots/review.py
Writes: docs/screenshots/REVIEW.md

Open it in a Markdown preview (VS Code: Cmd-Shift-V). The contact sheet at the
top is for scanning; the detail section below each thumbnail has the caption the
alt text uses, the page it lives on, and the setup steps it was shot under, so
you can tell "wrong screen" from "right screen, bad state".

Tick the `- [ ] retake` box under any shot that needs redoing, save, then run
retake.py — it reads the ticked boxes back out.
"""
import json
import os
import re
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "manifest.json")
OUT = os.path.join(HERE, "REVIEW.md")

COLUMNS = 4
THUMB = 170
DETAIL = 300


def slug(shot_id):
    """Stable anchor for a shot id — `smart/blacklist-editor` -> `shot-smart-blacklist-editor`."""
    return "shot-" + re.sub(r"[^a-z0-9]+", "-", shot_id.lower()).strip("-")


def section(shot_id):
    return shot_id.split("/")[0]


def asset_href(entry):
    """Path to the image relative to REVIEW.md, which sits in docs/screenshots/."""
    return "../" + entry["file"]


def main():
    manifest = json.load(open(MANIFEST))
    done = [e for e in manifest if e["status"] == "done"]

    groups = defaultdict(list)
    for entry in done:
        groups[section(entry["id"])].append(entry)
    ordered = sorted(groups.items())

    missing = [e for e in done if not os.path.exists(os.path.join(DOCS, e["file"]))]
    todo = sum(1 for e in manifest if e["status"] != "done")

    lines = [
        "# Screenshot review",
        "",
        f"{len(done)} shots taken, {todo} still to go. Generated by `review.py` — "
        "re-run it after any import to pick up new shots.",
        "",
        "**How to use this:** open in a Markdown preview, scan the contact sheet, "
        "click a thumbnail to jump to its details. Tick the **retake** checkbox "
        "under anything that looks wrong, save the file, then run:",
        "",
        "```bash",
        "python3 docs/screenshots/retake.py",
        "```",
        "",
        "That reads the ticked boxes and hands you the guide + import commands for "
        "exactly those shots. Retaking overwrites the image in place — the page "
        "already points at that path, so nothing else has to change.",
        "",
    ]

    if missing:
        lines += [
            "> **Warning:** these are marked done but the file is gone — "
            + ", ".join(f"`{e['id']}`" for e in missing),
            "",
        ]

    lines += ["## Contact sheet", ""]

    for name, entries in ordered:
        lines += [f"### {name}/  ({len(entries)})", "", "<table>"]
        for start in range(0, len(entries), COLUMNS):
            row = entries[start:start + COLUMNS]
            lines.append("<tr>")
            for entry in row:
                lines.append(
                    f'<td align="center" width="{THUMB + 20}">'
                    f'<a href="#{slug(entry["id"])}">'
                    f'<img src="{asset_href(entry)}" width="{THUMB}"></a></td>'
                )
            lines.append("</tr>")
            lines.append("<tr>")
            for entry in row:
                tail = entry["id"].split("/", 1)[-1]
                lines.append(f'<td align="center"><sub><code>{tail}</code></sub></td>')
            lines.append("</tr>")
        lines += ["</table>", ""]

    lines += ["---", "", "## Details", ""]

    for name, entries in ordered:
        lines += [f"## {name}/", ""]
        for entry in entries:
            lines += [
                f'<a id="{slug(entry["id"])}"></a>',
                "",
                f"### `{entry['id']}`",
                "",
                "- [ ] retake",
                "",
                f'<img src="{asset_href(entry)}" width="{DETAIL}">',
                "",
                f"**Caption (alt text):** {entry['caption']}",
                "",
                f"**Page:** `{entry['page']}`",
                "",
                f"**File:** `docs/{entry['file']}`",
                "",
            ]
            if entry.get("setup"):
                lines.append("**Shot under:**")
                lines.append("")
                for step in entry["setup"]:
                    lines.append(f"- {step}")
                lines.append("")
            if entry.get("notes"):
                lines += [f"> {entry['notes']}", ""]
            lines += ["---", ""]

    with open(OUT, "w") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {OUT} — {len(done)} shots across {len(ordered)} sections")
    for name, entries in ordered:
        print(f"  {len(entries):4}  {name}/")


if __name__ == "__main__":
    main()
