#!/usr/bin/env python3
"""Generate SHOOTLIST.md — the ordered, grouped checklist of screenshots still to take.

Usage:  python3 docs/screenshots/shootlist.py
Writes: docs/screenshots/SHOOTLIST.md

Batches are ordered so each one shares a navigation target: get to that screen
once, then take every shot in the batch top to bottom without leaving it.
The order inside a batch is the order import.py expects the photos in.
"""
import json
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "manifest.json")
OUT = os.path.join(HERE, "SHOOTLIST.md")


def bucket(entry):
    """Which screen you have to be on to take this shot."""
    text = (" ".join(entry.get("setup", [])) + " " + (entry.get("notes") or "")).lower()
    routes = [
        ("settings/themes", "settings-themes", "Settings › Appearance › Keyboard themes"),
        ("settings/languages", "settings-languages", "Settings › Languages"),
        ("settings/typing", "settings-typing", "Settings › Typing"),
        ("settings/tools", "settings-tools", "Settings › Tools"),
        ("settings/appearance", "settings-appearance", "Settings › Appearance"),
        ("settings/search", "settings-search", "Settings › Search"),
    ]
    if "docsshotactivity" in text or entry.get("host", "").startswith("harness"):
        return ("keyboard", "Keyboard itself (DocsShotActivity harness)")
    for needle, slug, label in routes:
        if needle in text:
            return (slug, label)
    if "addon" in entry["id"] or "addon" in text:
        return ("settings-addons", "Settings › Addons")
    if entry["id"].startswith("emoji/"):
        return ("keyboard-emoji", "Keyboard › emoji panel")
    return ("manual", "Manual navigation (see per-shot setup)")


def main():
    manifest = json.load(open(MANIFEST))
    todo = [e for e in manifest if e["status"] != "done"]

    groups = defaultdict(list)
    for entry in todo:
        groups[bucket(entry)].append(entry)

    ordered = sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0][0]))

    lines = [
        "# Screenshot shoot list",
        "",
        f"{len(todo)} shots left. Generated by `shootlist.py` — re-run it any time to "
        "regenerate with the remaining shots only.",
        "",
        "## How to use this",
        "",
        "1. Pick one batch below and get to the screen named in its heading.",
        "2. Take the shots **in the listed order**, one device screenshot each "
        "(Power + Volume-Down).",
        "3. Don't take any other screenshots in between — order is how they get matched up.",
        "4. Run the import command printed at the top of the batch.",
        "5. If you skip a shot, note which number you skipped and pass "
        "`--skip N` (repeatable) to the import command.",
        "",
        "Shots go to `/sdcard/DCIM/Screenshots` on the device; the importer pulls the "
        "newest N, converts them to WebP, drops them in the right asset folder, swaps the "
        "placeholder in the page, and marks the manifest entry done.",
        "",
        "---",
        "",
    ]

    for (slug, label), entries in ordered:
        lines.append(f"## {label}  ({len(entries)} shots)")
        lines.append("")
        lines.append("```bash")
        lines.append(f"python3 docs/screenshots/import.py {slug}")
        lines.append("```")
        lines.append("")
        for num, entry in enumerate(entries, 1):
            lines.append(f"### {num}. `{entry['id']}`")
            lines.append("")
            lines.append(f"**Shot:** {entry['caption']}")
            lines.append("")
            for step in entry.get("setup", []):
                lines.append(f"- {step}")
            if entry.get("notes"):
                lines.append("")
                lines.append(f"> {entry['notes']}")
            if entry.get("kind") == "anim":
                lines.append("")
                lines.append("> **Animated** — record a short clip instead of a still.")
            lines.append("")
        lines.append("---")
        lines.append("")

    with open(OUT, "w") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {OUT} — {len(todo)} shots across {len(ordered)} batches")
    for (slug, label), entries in ordered:
        print(f"  {len(entries):4}  {slug:22} {label}")


if __name__ == "__main__":
    main()
