#!/usr/bin/env python3
"""Regenerates InkModelTags.kt from ML Kit's digital-ink library.

ML Kit's `DigitalInkRecognitionModelIdentifier.allModelIdentifiers()` is the
catalogue the handwriting tool maps the keyboard's languages onto. On Play
that class lives in the on-demand :feature:handwriting module, and the
mapping has to work before the module is fetched (the panel must know which
language it is offering to download), so the tag list is compiled into the
base as a constant. The list is the same static table the library carries
in its `packmapping.pb` asset, minus the `-x-` private-use entries (gesture,
emoji, shapes, autodraw), which are not languages.

Run after bumping `mlkitDigitalInk` in gradle/libs.versions.toml, once Gradle
has downloaded the new AAR:

    python3 tools/handwriting/gen_ink_models.py

InkModelTagsTest (testFull in :core:intelligence) fails when the constant and
the library disagree.
"""

import glob
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CATALOG = os.path.join(ROOT, "gradle", "libs.versions.toml")
TARGET = os.path.join(
    ROOT, "core", "intelligence", "src", "full", "java",
    "com", "wasimaster", "wmkeyboard", "core", "handwriting", "InkModelTags.kt",
)


def version() -> str:
    with open(CATALOG, encoding="utf-8") as f:
        match = re.search(r'^mlkitDigitalInk\s*=\s*"([^"]+)"', f.read(), re.M)
    if not match:
        sys.exit("mlkitDigitalInk not found in libs.versions.toml")
    return match.group(1)


def aar_path(ver: str) -> str:
    pattern = os.path.expanduser(
        f"~/.gradle/caches/modules-2/files-2.1/com.google.mlkit/digital-ink-recognition/{ver}/*/digital-ink-recognition-{ver}.aar"
    )
    found = glob.glob(pattern)
    if not found:
        sys.exit(f"digital-ink-recognition-{ver}.aar is not in the Gradle cache; build once first")
    return found[0]


def varint(data: bytes, i: int):
    result = 0
    shift = 0
    while True:
        byte = data[i]
        i += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, i
        shift += 7


def fields(data: bytes, start: int, end: int):
    """Every field in a message made only of length-delimited fields."""
    i = start
    while i < end:
        key, i = varint(data, i)
        if key & 7 != 2:
            sys.exit("packmapping.pb has a field that is not length-delimited; the format moved")
        length, i = varint(data, i)
        yield key >> 3, data[i:i + length]
        i += length


# The recogniser each model runs on, named in packmapping.pb's field 6 as
# `[indy_]lstm_<family>_...`, and the ISO 15924 script that family reads. The
# library's own identifier reports this script for every tag, spelled out or
# not (`af` reads as Latn), and `tagFor` compares it against the keyboard's
# script ids, so the constant carries it too. A family missing here fails the
# run rather than guessing.
FAMILY_SCRIPTS = {
    "arabic": "Arab", "armenian": "Armn", "bengali": "Beng", "chinese": "Hani",
    "cyrillic": "Cyrl", "devanagari": "Deva", "ethiopic": "Ethi", "georgian": "Geor",
    "greek": "Grek", "gujarati": "Gujr", "hebrew": "Hebr", "japanese": "Jpan",
    "kannada": "Knda", "khmer": "Khmr", "korean": "Kore", "lao": "Laoo",
    "latin": "Latn", "malayalam": "Mlym", "myanmar": "Mymr", "odia": "Orya",
    "punjabi": "Guru", "sinhala": "Sinh", "tamil": "Taml", "telugu": "Telu",
    "thai": "Thai", "tibetan": "Tibt", "vietnamese": "Latn",
}

FAMILY_RE = re.compile(r"(?:indy_)?lstm_([a-z_]+?)_(?:\d|tflite)")


def tags(aar: str) -> dict:
    """Language tag -> script, for every non-`-x-` entry."""
    with zipfile.ZipFile(aar) as zf:
        data = zf.read("assets/packmapping.pb")
    out = {}
    for field, entry in fields(data, 0, len(data)):
        if field != 1:
            continue
        tag = None
        recogniser = None
        for inner, value in fields(entry, 0, len(entry)):
            text = value.decode("utf-8")
            if inner == 1:
                tag = text
            elif inner == 6:
                recogniser = text
        if tag is None or "-x-" in tag:
            continue
        match = FAMILY_RE.match(recogniser or "")
        if not match:
            sys.exit(f"{tag}: recogniser pack {recogniser!r} names no family")
        family = match.group(1)
        if family not in FAMILY_SCRIPTS:
            sys.exit(f"{tag}: recogniser family {family!r} has no script in FAMILY_SCRIPTS")
        out[tag] = FAMILY_SCRIPTS[family]
    return dict(sorted(out.items()))


def main() -> None:
    ver = version()
    all_tags = tags(aar_path(ver))
    lines = [
        "package com.wasimaster.wmkeyboard.core.handwriting",
        "",
        "// GENERATED by tools/handwriting/gen_ink_models.py from",
        f"// digital-ink-recognition {ver}. Do not edit; rerun the script after a bump.",
        "",
        "/**",
        " * Every language ML Kit's ink recogniser has a model for, as its BCP-47",
        " * tag, with the script that model reads: the library's own catalogue with",
        " * the `-x-` non-language entries (gesture, emoji, shapes, autodraw) left",
        " * out. Compiled in rather than asked of the library because on Play the",
        " * library is an on-demand module, and the tool has to know which language",
        " * it is offering to download before that module is here. InkModelTagsTest",
        " * keeps it honest.",
        " */",
        "internal object InkModelTags {",
        "",
        f"    const val LIBRARY_VERSION = \"{ver}\"",
        "",
        "    /** Tag to the ISO 15924 script its recogniser reads, sorted by tag. */",
        "    val SCRIPTS: Map<String, String> = mapOf(",
    ]
    for tag, script in all_tags.items():
        lines.append(f'        "{tag}" to "{script}",')
    lines += ["    )", "", "    val ALL: List<String> get() = SCRIPTS.keys.toList()", "}", ""]
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(all_tags)} tags from digital-ink-recognition {ver} -> {os.path.relpath(TARGET, ROOT)}")


if __name__ == "__main__":
    main()
