// Generated by scripts/gen_symbol_icons.py from Material Symbols (Apache 2.0). Do not edit.
@file:Suppress("ObjectPropertyName", "TopLevelPropertyNaming", "VariableNaming", "MaxLineLength")

package com.wasimaster.wmkeyboard.core.icons.symbols.rounded

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.vector.ImageVector
import com.wasimaster.wmkeyboard.core.icons.symbolVector

/** Material Symbols `check`. */
val Icons.Rounded.Check: ImageVector
    get() = _check ?: symbolVector("Rounded.Check", """m382-354 339-339q12-12 28-12t28 12q12 12 12 28.5T777-636L410-268q-12 12-28 12t-28-12L182-440q-12-12-11.5-28.5T183-497q12-12 28.5-12t28.5 12l142 143Z""", autoMirror = false)
        .also { _check = it }
private var _check: ImageVector? = null

/** Material Symbols `check_circle`. */
val Icons.Rounded.CheckCircle: ImageVector
    get() = _checkCircle ?: symbolVector("Rounded.CheckCircle", """m424-408-86-86q-11-11-28-11t-28 11q-11 11-11 28t11 28l114 114q12 12 28 12t28-12l226-226q11-11 11-28t-11-28q-11-11-28-11t-28 11L424-408Zm56 328q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z""", autoMirror = false)
        .also { _checkCircle = it }
private var _checkCircle: ImageVector? = null
