package com.wasimaster.wmkeyboard.core.emoji

import java.io.InputStream

/**
 * Which emoji Google publishes an animated version of, and where to fetch it.
 *
 * The set is bundled (`emoji/animated.txt`, generated by
 * `tools/emoji/generate_animated.py`) rather than probed, because coverage is
 * partial — roughly 900 of the catalogue, with no flags and few sequences — and
 * asking the server would mean a 404 round trip on every long press that has no
 * animation to offer.
 *
 * The assets are Noto Animated Emoji by Google, licensed CC BY 4.0. Anywhere
 * the app offers one it also says so.
 */
class AnimatedEmoji private constructor(private val codes: Set<String>) {

    val isEmpty: Boolean get() = codes.isEmpty()

    /**
     * The asset key for [emoji], or null when nothing is published for it.
     *
     * Four spellings are tried, closest match first. The index disagrees with
     * itself about variation selectors — ❤️ is `2764_fe0f`, 😀 is plain
     * `1f600` — and a keyboard's own spelling of either may go the other way,
     * so both directions are tried. Skin tones are dropped last of all: most
     * toned emoji have their own animation, and the neutral one is only a
     * stand-in for the few that do not.
     */
    fun keyFor(emoji: String): String? {
        if (codes.isEmpty() || emoji.isEmpty()) return null
        val codePoints = EmojiFontShaping.codePoints(emoji)
        return codes.firstMatch(codePoints)
            ?: codes.firstMatch(codePoints.filterNot(::isSelector))
            ?: codes.firstMatch(codePoints.withSelector())
            ?: codes.firstMatch(codePoints.filterNot { isSelector(it) || isSkinTone(it) })
    }

    /** The 512×512 GIF for a key from [keyFor] — what actually gets sent. */
    fun gifUrl(key: String): String = "$ASSET_BASE/$key/512.gif"

    /**
     * The same animation as WebP: a third of the GIF's size for the same
     * frames, which is what the preview wants. Not what gets sent — plenty of
     * apps take an `image/webp` and then draw only its first frame.
     */
    fun webpUrl(key: String): String = "$ASSET_BASE/$key/512.webp"

    private fun Set<String>.firstMatch(codePoints: IntArray): String? =
        spell(codePoints)?.takeIf { it in this }

    companion object {

        val EMPTY = AnimatedEmoji(emptySet())

        private const val ASSET_BASE = "https://fonts.gstatic.com/s/e/notoemoji/latest"

        /** Format: one code point spelling per line, `# ` comments. */
        fun load(stream: InputStream): AnimatedEmoji {
            val codes = HashSet<String>(1024)
            stream.bufferedReader().useLines { lines ->
                for (line in lines) {
                    val trimmed = line.trim()
                    if (trimmed.isEmpty() || trimmed.startsWith("#")) continue
                    codes.add(trimmed)
                }
            }
            return AnimatedEmoji(codes)
        }

        private fun spell(codePoints: IntArray): String? {
            if (codePoints.isEmpty()) return null
            return codePoints.joinToString("_") { it.toString(16) }
        }

        private fun IntArray.filterNot(drop: (Int) -> Boolean): IntArray {
            val out = IntArray(size)
            var n = 0
            for (cp in this) if (!drop(cp)) out[n++] = cp
            return if (n == size) this else out.copyOf(n)
        }

        /**
         * The one-code-point spelling with U+FE0F added, for the bare form of
         * an emoji the index only names with its selector (❤ → `2764_fe0f`).
         * Anything longer is left alone: where the selector belongs in a ZWJ
         * sequence is the sequence's business, not this function's guess.
         */
        private fun IntArray.withSelector(): IntArray =
            if (size == 1 && !isSelector(this[0])) intArrayOf(this[0], 0xFE0F) else this

        private fun isSelector(codePoint: Int) = codePoint == 0xFE0F || codePoint == 0xFE0E

        private fun isSkinTone(codePoint: Int) = codePoint in 0x1F3FB..0x1F3FF
    }
}
