package com.wasimaster.wmkeyboard.core.emoji

import java.io.InputStream

/**
 * `:tada:`-style emoji shortcodes — the names people already type in GitHub
 * Markdown, Discord and Slack.
 *
 * These are worth carrying separately from the catalog's CLDR keywords
 * because the two disagree on exactly the names that get typed most: the
 * Unicode name for 😂 is "face with tears of joy" and for 🎉 "party popper",
 * but everyone types `:joy:` and `:tada:`. Roughly a quarter of the shortcode
 * table is unreachable from keywords alone.
 *
 * Data comes from the bundled `emoji/shortcodes.tsv`, generated by
 * `tools/emoji/generate_gemoji.py` out of github/gemoji plus the handful
 * of Discord/Slack spellings gemoji lacks.
 */
class EmojiShortcodes private constructor(
    private val byCode: Map<String, String>,
    /** Shortcodes in sorted order, so a prefix is one binary search away. */
    private val codes: List<String>,
) {

    val isEmpty: Boolean get() = byCode.isEmpty()

    /** The emoji for an exact shortcode, with or without its colons. */
    fun exact(code: String): String? = byCode[normalize(code)]

    /**
     * Emoji whose shortcode starts with [code], shortest name first — typing
     * `:sm` offers 😄 (`smile`) ahead of 😅 (`smiling_face_with_tear`). Emoji
     * reached by more than one alias appear once.
     */
    fun prefix(code: String, limit: Int): List<String> {
        val query = normalize(code)
        if (query.isEmpty() || limit <= 0) return emptyList()
        // binarySearch returns the insertion point (negated, minus one) for a
        // miss; either way that index is the first code >= the query.
        val found = codes.binarySearch(query)
        var i = if (found >= 0) found else -(found + 1)
        val matches = ArrayList<String>()
        while (i < codes.size && codes[i].startsWith(query)) {
            matches.add(codes[i])
            i++
        }
        return matches
            .sortedWith(compareBy({ it.length }, { it }))
            .mapNotNull { byCode[it] }
            .distinct()
            .take(limit)
    }

    companion object {

        val EMPTY = EmojiShortcodes(emptyMap(), emptyList())

        /**
         * Trims the colons people type around a shortcode and lowercases it,
         * so `:TADA:`, `:tada` and `tada` all look the same to a lookup.
         */
        fun normalize(raw: String): String =
            raw.trim().lowercase().removePrefix(":").removeSuffix(":")

        /** Format: `shortcode<TAB>emoji`, one per line, `# ` comments. */
        fun load(stream: InputStream): EmojiShortcodes {
            val byCode = HashMap<String, String>()
            stream.bufferedReader().useLines { lines ->
                for (line in lines) {
                    if (line.isBlank() || line.startsWith("# ")) continue
                    val tab = line.indexOf('\t')
                    if (tab <= 0) continue
                    val code = line.substring(0, tab).trim().lowercase()
                    val emoji = line.substring(tab + 1).trim()
                    if (code.isNotEmpty() && emoji.isNotEmpty()) byCode[code] = emoji
                }
            }
            return EmojiShortcodes(byCode, byCode.keys.sorted())
        }
    }
}
