/** Port of LuaApiDocs.kt, verbatim: one paragraph per LuaApi path. */

const docs: Record<string, string> = {
	_G: 'The table of global variables. Reading _G.name is the same as reading name.',
	_VERSION: 'The Lua version, as text.',
	assert: 'Raises an error with message when value is false or nil. Returns all its arguments otherwise.',
	error: 'Stops the current call with message. The plugin stays loaded and the message goes to the log.',
	getmetatable: 'The metatable of value, or nil. For a string it is the text "protected", because the string metatable is frozen.',
	setmetatable: 'Sets the metatable of table and returns table.',
	ipairs: 'Walks a list in order: for i, value in ipairs(list) do ... end. Stops at the first nil.',
	pairs: 'Walks every key of a table in no fixed order: for key, value in pairs(t) do ... end.',
	next: 'The key after key in table, and its value. Nil at the end.',
	pcall: 'Calls f with the arguments and catches an error. Returns true and the results, or false and the error.',
	xpcall: 'Like pcall, but passes an error to handler first.',
	rawequal: 'Whether a and b are the same value, without metamethods.',
	rawget: 'table[key], without metamethods.',
	rawlen: 'The length of a table or string, without metamethods.',
	rawset: 'Sets table[key] = value, without metamethods.',
	select: 'With a number, the arguments from position n. With "#", how many arguments there are.',
	tonumber: 'value as a number, or nil when it is not one. base reads text in another base, from 2 to 36.',
	tostring: 'value as text.',
	type: 'The type of value as text: "nil", "number", "string", "boolean", "table" or "function".',
	print: 'Writes its arguments as one line of the plugin log. The plugin editor shows it in the console.',
	collectgarbage: 'Does nothing and returns 0. Memory is managed for the plugin.',
	string: 'Text functions. Also reachable as methods: s:upper() is string.upper(s).',
	table: 'Functions for lists and tables.',
	math: 'Mathematical functions and constants.',
	bit32: 'Bitwise operations on 32-bit numbers.',
	os: 'A reduced os library: time, clock and date only.',
	ui: 'Builds the widgets render() returns. Each function returns a plain table; you can write the table yourself.',
	wm: 'The whole host API: log, json, ui and, with the storage permission, storage. There is no way to read text, the clipboard, files or the network.',

	'string.byte': 'The character codes of s from i to j.',
	'string.char': 'A string made of the given character codes.',
	'string.dump': 'Always fails in a plugin: compiled Lua cannot be loaded, so there is nothing to dump to.',
	'string.find': 'Where pattern first matches in s, from init: start and end positions, then any captures. plain = true searches for the text itself.',
	'string.format': 'Text built from a format and values, like C printf: %d, %s, %5.2f.',
	'string.gmatch': 'An iterator over each match of pattern in s: for word in s:gmatch("%a+") do ... end.',
	'string.gsub': 's with each match of pattern replaced, and how many were replaced. replacement can be text, a table or a function.',
	'string.len': 'The length of s in bytes. Use #s for the same thing.',
	'string.lower': 's in small letters.',
	'string.match': 'The captures of the first match of pattern in s, or the whole match when there are none.',
	'string.rep': 's repeated n times, with separator between. Stops with an error above 256 KB.',
	'string.reverse': 's back to front, byte by byte.',
	'string.sub': 'The part of s from i to j. Negative positions count from the end.',
	'string.upper': 's in capital letters.',

	'table.concat': 'The items of list joined into one string with separator. Stops with an error above 1 MB.',
	'table.insert': 'Adds value to list, at the end or at position.',
	'table.pack': 'The arguments in a new table, with n set to how many there are.',
	'table.remove': 'Removes and returns the item at position, or the last item.',
	'table.sort': 'Sorts list in place, with comparator(a, b) returning true when a comes first.',
	'table.unpack': 'The items of list as separate values. In Lua 5.2 there is no global unpack.',

	'math.abs': 'The absolute value of x.',
	'math.acos': 'The arc cosine of x, in radians.',
	'math.asin': 'The arc sine of x, in radians.',
	'math.atan': 'The arc tangent of x, in radians.',
	'math.atan2': 'The arc tangent of y / x, in radians, using the signs of both to find the quadrant.',
	'math.ceil': 'The smallest whole number not less than x.',
	'math.cos': 'The cosine of x, in radians.',
	'math.cosh': 'The hyperbolic cosine of x.',
	'math.deg': 'x radians in degrees.',
	'math.exp': 'e to the power x.',
	'math.floor': 'The largest whole number not greater than x.',
	'math.fmod': 'The remainder of x / y, with the sign of x.',
	'math.frexp': 'm and e such that x = m * 2 ^ e.',
	'math.huge': 'A number larger than any other.',
	'math.ldexp': 'm * 2 ^ e.',
	'math.log': 'The logarithm of x, natural or in base. There is no math.log10; use math.log(x, 10).',
	'math.max': 'The largest of its arguments.',
	'math.min': 'The smallest of its arguments.',
	'math.modf': 'The whole and fractional parts of x.',
	'math.pi': 'The number pi.',
	'math.pow': 'x to the power y. The same as x ^ y.',
	'math.rad': 'x degrees in radians.',
	'math.random': 'A random number: from 0 to 1 with no arguments, from 1 to m, or from m to n.',
	'math.randomseed': 'Sets the seed of math.random.',
	'math.sin': 'The sine of x, in radians.',
	'math.sinh': 'The hyperbolic sine of x.',
	'math.sqrt': 'The square root of x.',
	'math.tan': 'The tangent of x, in radians.',
	'math.tanh': 'The hyperbolic tangent of x.',

	'bit32.arshift': 'x shifted right by shift, keeping the sign bit.',
	'bit32.band': 'The bitwise and of its arguments.',
	'bit32.bnot': 'The bitwise not of x.',
	'bit32.bor': 'The bitwise or of its arguments.',
	'bit32.btest': 'Whether the bitwise and of its arguments is not zero.',
	'bit32.bxor': 'The bitwise exclusive or of its arguments.',
	'bit32.extract': 'The bits of n from field, width bits wide.',
	'bit32.lrotate': 'x rotated left by shift.',
	'bit32.lshift': 'x shifted left by shift.',
	'bit32.replace': 'n with the bits from field, width bits wide, set to value.',
	'bit32.rrotate': 'x rotated right by shift.',
	'bit32.rshift': 'x shifted right by shift.',

	'os.clock': 'Seconds since this plugin session started.',
	'os.date': 'The date as text, or as a table with "*t". Understands %Y %y %m %d %H %M %S %j %p %A %a %B %b %c %x %X and %%, and a leading ! for UTC.',
	'os.time': 'The time now, in seconds. It always gives the time now and does not read a table.',

	'wm.api_version': 'The API level this keyboard gives plugins. Now 1.',
	'wm.plugin_id': 'The id from your manifest.',
	'wm.plugin_version': 'The pluginVersion from your manifest.',
	'wm.log': 'Writes message as one line of your plugin log, readable in Settings and in the editor console.',
	'wm.json': 'JSON to and from Lua tables.',
	'wm.json.decode': 'text read as JSON: a table, text, number or boolean. On failure, nil and a reason.',
	'wm.json.encode': 'value written as JSON text. A table with keys 1 to n becomes an array. On failure, nil and a reason.',
	'wm.ui': 'Writes to your own widgets.',
	'wm.ui.set_input': 'Puts text in your input widget id. Applied after your handler returns. Up to 8 KB.',
	'wm.storage': 'Text saved on this device for your plugin, kept across sessions and deleted on uninstall. Only there when the manifest declares the storage permission; otherwise nil.',
	'wm.storage.get': 'The text saved under key, or nil.',
	'wm.storage.set': 'Saves value under key. Returns true, or nil and a reason when over the quota: 128 keys, 64 characters a key, 8 KB a value, 64 KB in all.',
	'wm.storage.remove': 'Deletes key.',
	'wm.storage.keys': 'A list of every saved key.',

	'ui.column': 'Widgets stacked top to bottom. Put the children in the table: ui.column { ui.label { text = "a" }, ui.label { text = "b" } }.',
	'ui.row': 'Widgets side by side, sharing the width equally.',
	'ui.label': 'Text. style is "title", "body" or "caption"; body is the default.',
	'ui.output': "A result, with the keyboard's own Insert and Copy buttons under it. Insert is the only way your result reaches the user's text. insertable and copyable are on unless set to false; mono draws the text monospaced.",
	'ui.button': 'A button. on_event hears { type = "click", id = id }. style = "primary" highlights it; enabled = false greys it out.',
	'ui.toggle': 'A switch. on_event hears { type = "toggle", id = id, value = true or false }.',
	'ui.input': 'A text box the keyboard owns. on_event hears { type = "input_changed", id = id, value = text } after each change. Write to it with wm.ui.set_input.',
	'ui.spacer': 'Empty space, height from 0 to 64. 8 when not given.',
	'ui.divider': 'A line across the panel.',
	'ui.progress': 'An indeterminate bar that shows something is happening.',
	'ui.tabs': 'A tab strip, top level only, up to 8 pages. Put ui.page tables in it. on_event hears { type = "tab_selected", id = id, index = n }, counting from 0.',
	'ui.page': 'One page of ui.tabs: a title, and its widgets in the table.',
};

export function docOf(path: string): string | undefined {
	return docs[path];
}
