const KEYMAN_VERSION = { VERSION: '19.0.0', VERSION_MAJOR: '19', VERSION_MINOR: '0', VERSION_PATCH: '0', VERSION_RELEASE: '19.0', VERSION_WITH_TAG: '19.0.0', VERSION_ENVIRONMENT: 'local', VERSION_GIT_TAG: '', TIER: 'alpha', VERSION_TAG: '' };
export default KEYMAN_VERSION;
