#!/usr/bin/env bash
# Trailer footage capture rig. Records 1080x2400 clips via scrcpy (the
# on-device `screenrecord` binary is blocked on ColorOS — "Permission denied"
# for any output path), trims/normalizes into public/clips/, and regenerates
# src/clips.ts so scenes pick them up.
#
# Usage:
#   ./record.sh start <name> [seconds]   # record footage/<name>.mp4 (default 8s)
#   ./record.sh trim <name> <ss> <to>    # ffmpeg trim footage -> public/clips
#   ./record.sh manifest                 # regenerate src/clips.ts
#   ./record.sh demo on|off              # SystemUI demo mode (clean statusbar)
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p footage public/clips

case "${1:-}" in
  start)
    NAME="${2:?name}"; SECS="${3:-8}"
    scrcpy --no-playback --no-audio --record="footage/$NAME.mp4" --time-limit="$SECS"
    ;;
  trim)
    NAME="${2:?name}"; SS="${3:-0}"; TO="${4:-}"
    TOARG=(); [ -n "$TO" ] && TOARG=(-to "$TO")
    # scrcpy output is variable-frame-rate; force CFR 30 for Remotion.
    ffmpeg -y -ss "$SS" "${TOARG[@]}" -i "footage/$NAME.mp4" \
      -c:v libx264 -preset slow -crf 20 -pix_fmt yuv420p -r 30 -fps_mode cfr \
      -an -movflags +faststart "public/clips/$NAME.mp4"
    "$0" manifest
    ;;
  manifest)
    {
      echo "// Regenerated by record.sh (gen_manifest) — lists files present in public/clips."
      echo "// Scenes fall back to a placeholder panel for clips not yet captured."
      echo "export const AVAILABLE_CLIPS: string[] = ["
      for f in public/clips/*.mp4; do
        [ -e "$f" ] && echo "  \"$(basename "$f")\","
      done
      echo "];"
      echo ""
      echo "// Set to a filename in public/ (e.g. \"music.mp3\") to mix a soundtrack."
      if [ -e public/music.mp3 ]; then
        echo "export const MUSIC: string | null = \"music.mp3\";"
      else
        echo "export const MUSIC: string | null = null;"
      fi
    } > src/clips.ts
    echo "wrote src/clips.ts"
    ;;
  demo)
    if [ "${2:-on}" = "on" ]; then
      adb shell settings put global sysui_demo_allowed 1
      adb shell am broadcast -a com.android.systemui.demo -e command enter
      adb shell am broadcast -a com.android.systemui.demo -e command clock -e hhmm 0100
      adb shell am broadcast -a com.android.systemui.demo -e command battery -e level 100 -e plugged false
      adb shell am broadcast -a com.android.systemui.demo -e command network -e wifi show -e level 4
      adb shell am broadcast -a com.android.systemui.demo -e command notifications -e visible false
    else
      adb shell am broadcast -a com.android.systemui.demo -e command exit
    fi
    ;;
  *)
    echo "usage: record.sh start|pull|trim|manifest|demo" >&2; exit 1
    ;;
esac
