// Generated by scripts/gen_symbol_icons.py from Material Symbols (Apache 2.0). Do not edit.
@file:Suppress("ObjectPropertyName", "TopLevelPropertyNaming", "VariableNaming", "MaxLineLength")

package com.wasimaster.wmkeyboard.core.icons.symbols.automirrored.outlined

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.vector.ImageVector
import com.wasimaster.wmkeyboard.core.icons.symbolVector

/** Material Symbols `arrow_back`. */
val Icons.AutoMirrored.Outlined.ArrowBack: ImageVector
    get() = _arrowBack ?: symbolVector("AutoMirrored.Outlined.ArrowBack", """m313-440 196 196q12 12 11.5 28T508-188q-12 11-28 11.5T452-188L188-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l264-264q11-11 27.5-11t28.5 11q12 12 12 28.5T508-715L313-520h447q17 0 28.5 11.5T800-480q0 17-11.5 28.5T760-440H313Z""", autoMirror = true)
        .also { _arrowBack = it }
private var _arrowBack: ImageVector? = null

/** Material Symbols `arrow_forward`. */
val Icons.AutoMirrored.Outlined.ArrowForward: ImageVector
    get() = _arrowForward ?: symbolVector("AutoMirrored.Outlined.ArrowForward", """M647-440H200q-17 0-28.5-11.5T160-480q0-17 11.5-28.5T200-520h447L451-716q-12-12-11.5-28t12.5-28q12-11 28-11.5t28 11.5l264 264q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L508-188q-11 11-27.5 11T452-188q-12-12-12-28.5t12-28.5l195-195Z""", autoMirror = true)
        .also { _arrowForward = it }
private var _arrowForward: ImageVector? = null

/** Material Symbols `arrow_left`. */
val Icons.AutoMirrored.Outlined.ArrowLeft: ImageVector
    get() = _arrowLeft ?: symbolVector("AutoMirrored.Outlined.ArrowLeft", """M526-314 381-459q-5-5-7-10t-2-11q0-6 2-11t7-10l145-145q3-3 6.5-4.5t7.5-1.5q8 0 14 5.5t6 14.5v304q0 9-6 14.5t-14 5.5q-2 0-14-6Z""", autoMirror = true)
        .also { _arrowLeft = it }
private var _arrowLeft: ImageVector? = null

/** Material Symbols `arrow_right`. */
val Icons.AutoMirrored.Outlined.ArrowRight: ImageVector
    get() = _arrowRight ?: symbolVector("AutoMirrored.Outlined.ArrowRight", """M420-308q-8 0-14-5.5t-6-14.5v-304q0-9 6-14.5t14-5.5q2 0 14 6l145 145q5 5 7 10t2 11q0 6-2 11t-7 10L434-314q-3 3-6.5 4.5T420-308Z""", autoMirror = true)
        .also { _arrowRight = it }
private var _arrowRight: ImageVector? = null

/** Material Symbols `article`. */
val Icons.AutoMirrored.Outlined.Article: ImageVector
    get() = _article ?: symbolVector("AutoMirrored.Outlined.Article", """M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm0-560v560-560Zm120 480h200q17 0 28.5-11.5T560-320q0-17-11.5-28.5T520-360H320q-17 0-28.5 11.5T280-320q0 17 11.5 28.5T320-280Zm0-160h320q17 0 28.5-11.5T680-480q0-17-11.5-28.5T640-520H320q-17 0-28.5 11.5T280-480q0 17 11.5 28.5T320-440Zm0-160h320q17 0 28.5-11.5T680-640q0-17-11.5-28.5T640-680H320q-17 0-28.5 11.5T280-640q0 17 11.5 28.5T320-600Z""", autoMirror = true)
        .also { _article = it }
private var _article: ImageVector? = null

/** Material Symbols `assignment`. */
val Icons.AutoMirrored.Outlined.Assignment: ImageVector
    get() = _assignment ?: symbolVector("AutoMirrored.Outlined.Assignment", """M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h168q13-36 43.5-58t68.5-22q38 0 68.5 22t43.5 58h168q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm120-80h200q17 0 28.5-11.5T560-320q0-17-11.5-28.5T520-360H320q-17 0-28.5 11.5T280-320q0 17 11.5 28.5T320-280Zm0-160h320q17 0 28.5-11.5T680-480q0-17-11.5-28.5T640-520H320q-17 0-28.5 11.5T280-480q0 17 11.5 28.5T320-440Zm0-160h320q17 0 28.5-11.5T680-640q0-17-11.5-28.5T640-680H320q-17 0-28.5 11.5T280-640q0 17 11.5 28.5T320-600Zm181.5-198.5Q510-807 510-820t-8.5-21.5Q493-850 480-850t-21.5 8.5Q450-833 450-820t8.5 21.5Q467-790 480-790t21.5-8.5ZM200-200v-560 560Z""", autoMirror = true)
        .also { _assignment = it }
private var _assignment: ImageVector? = null

/** Material Symbols `backspace`. */
val Icons.AutoMirrored.Outlined.Backspace: ImageVector
    get() = _backspace ?: symbolVector("AutoMirrored.Outlined.Backspace", """m560-424 76 76q11 11 28 11t28-11q11-11 11-28t-11-28l-76-76 76-76q11-11 11-28t-11-28q-11-11-28-11t-28 11l-76 76-76-76q-11-11-28-11t-28 11q-11 11-11 28t11 28l76 76-76 76q-11 11-11 28t11 28q11 11 28 11t28-11l76-76ZM360-160q-19 0-36-8.5T296-192L116-432q-16-21-16-48t16-48l180-240q11-15 28-23.5t36-8.5h440q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H360Zm0-80h440v-480H360L180-480l180 240Zm130-240Z""", autoMirror = true)
        .also { _backspace = it }
private var _backspace: ImageVector? = null

/** Material Symbols `chat`. */
val Icons.AutoMirrored.Outlined.Chat: ImageVector
    get() = _chat ?: symbolVector("AutoMirrored.Outlined.Chat", """m240-240-92 92q-19 19-43.5 8.5T80-177v-623q0-33 23.5-56.5T160-880h640q33 0 56.5 23.5T880-800v480q0 33-23.5 56.5T800-240H240Zm-34-80h594v-480H160v525l46-45Zm-46 0v-480 480Zm120-80h240q17 0 28.5-11.5T560-440q0-17-11.5-28.5T520-480H280q-17 0-28.5 11.5T240-440q0 17 11.5 28.5T280-400Zm0-120h400q17 0 28.5-11.5T720-560q0-17-11.5-28.5T680-600H280q-17 0-28.5 11.5T240-560q0 17 11.5 28.5T280-520Zm0-120h400q17 0 28.5-11.5T720-680q0-17-11.5-28.5T680-720H280q-17 0-28.5 11.5T240-680q0 17 11.5 28.5T280-640Z""", autoMirror = true)
        .also { _chat = it }
private var _chat: ImageVector? = null

/** Material Symbols `compare_arrows`. */
val Icons.AutoMirrored.Outlined.CompareArrows: ImageVector
    get() = _compareArrows ?: symbolVector("AutoMirrored.Outlined.CompareArrows", """M367-320H120q-17 0-28.5-11.5T80-360q0-17 11.5-28.5T120-400h247l-75-75q-11-11-11-27.5t11-28.5q12-12 28.5-12t28.5 12l143 143q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L348-188q-12 12-28 11.5T292-189q-11-12-11.5-28t11.5-28l75-75Zm226-240 75 75q11 11 11 27.5T668-429q-12 12-28.5 12T611-429L468-572q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l144-144q12-12 28-11.5t28 12.5q11 12 11.5 28T668-715l-75 75h247q17 0 28.5 11.5T880-600q0 17-11.5 28.5T840-560H593Z""", autoMirror = true)
        .also { _compareArrows = it }
private var _compareArrows: ImageVector? = null

/** Material Symbols `fact_check`. */
val Icons.AutoMirrored.Outlined.FactCheck: ImageVector
    get() = _factCheck ?: symbolVector("AutoMirrored.Outlined.FactCheck", """M160-120q-33 0-56.5-23.5T80-200v-560q0-33 23.5-56.5T160-840h640q33 0 56.5 23.5T880-760v560q0 33-23.5 56.5T800-120H160Zm0-80h640v-560H160v560Zm200-80q17 0 28.5-11.5T400-320q0-17-11.5-28.5T360-360H240q-17 0-28.5 11.5T200-320q0 17 11.5 28.5T240-280h120Zm222-193-29-29q-12-12-28-11.5T497-501q-11 12-11.5 28t11.5 28l57 57q12 12 28 12t28-12l142-142q12-12 12-28t-12-28q-12-12-28.5-12T695-586L582-473Zm-222 33q17 0 28.5-11.5T400-480q0-17-11.5-28.5T360-520H240q-17 0-28.5 11.5T200-480q0 17 11.5 28.5T240-440h120Zm0-160q17 0 28.5-11.5T400-640q0-17-11.5-28.5T360-680H240q-17 0-28.5 11.5T200-640q0 17 11.5 28.5T240-600h120ZM160-200v-560 560Z""", autoMirror = true)
        .also { _factCheck = it }
private var _factCheck: ImageVector? = null

/** Material Symbols `format_align_left`. */
val Icons.AutoMirrored.Outlined.FormatAlignLeft: ImageVector
    get() = _formatAlignLeft ?: symbolVector("AutoMirrored.Outlined.FormatAlignLeft", """M160-120q-17 0-28.5-11.5T120-160q0-17 11.5-28.5T160-200h640q17 0 28.5 11.5T840-160q0 17-11.5 28.5T800-120H160Zm0-160q-17 0-28.5-11.5T120-320q0-17 11.5-28.5T160-360h400q17 0 28.5 11.5T600-320q0 17-11.5 28.5T560-280H160Zm0-160q-17 0-28.5-11.5T120-480q0-17 11.5-28.5T160-520h640q17 0 28.5 11.5T840-480q0 17-11.5 28.5T800-440H160Zm0-160q-17 0-28.5-11.5T120-640q0-17 11.5-28.5T160-680h400q17 0 28.5 11.5T600-640q0 17-11.5 28.5T560-600H160Zm0-160q-17 0-28.5-11.5T120-800q0-17 11.5-28.5T160-840h640q17 0 28.5 11.5T840-800q0 17-11.5 28.5T800-760H160Z""", autoMirror = true)
        .also { _formatAlignLeft = it }
private var _formatAlignLeft: ImageVector? = null

/** Material Symbols `format_indent_increase`. */
val Icons.AutoMirrored.Outlined.FormatIndentIncrease: ImageVector
    get() = _formatIndentIncrease ?: symbolVector("AutoMirrored.Outlined.FormatIndentIncrease", """M160-120q-17 0-28.5-11.5T120-160q0-17 11.5-28.5T160-200h640q17 0 28.5 11.5T840-160q0 17-11.5 28.5T800-120H160Zm320-160q-17 0-28.5-11.5T440-320q0-17 11.5-28.5T480-360h320q17 0 28.5 11.5T840-320q0 17-11.5 28.5T800-280H480Zm0-160q-17 0-28.5-11.5T440-480q0-17 11.5-28.5T480-520h320q17 0 28.5 11.5T840-480q0 17-11.5 28.5T800-440H480Zm0-160q-17 0-28.5-11.5T440-640q0-17 11.5-28.5T480-680h320q17 0 28.5 11.5T840-640q0 17-11.5 28.5T800-600H480ZM160-760q-17 0-28.5-11.5T120-800q0-17 11.5-28.5T160-840h640q17 0 28.5 11.5T840-800q0 17-11.5 28.5T800-760H160Zm-6 406q-10 10-22 5t-12-19v-224q0-14 12-19t22 5l112 112q6 6 6 14t-6 14L154-354Z""", autoMirror = true)
        .also { _formatIndentIncrease = it }
private var _formatIndentIncrease: ImageVector? = null

/** Material Symbols `format_textdirection_r_to_l`. */
val Icons.AutoMirrored.Outlined.FormatTextdirectionRToL: ImageVector
    get() = _formatTextdirectionRToL ?: symbolVector("AutoMirrored.Outlined.FormatTextdirectionRToL", """M440-800v400q0 17-11.5 28.5T400-360q-17 0-28.5-11.5T360-400v-160q-66 0-113-47t-47-113q0-66 47-113t113-47h280q17 0 28.5 11.5T680-840q0 17-11.5 28.5T640-800h-40v400q0 17-11.5 28.5T560-360q-17 0-28.5-11.5T520-400v-400h-80ZM272-200l36 36q11 11 11 28t-11 28q-11 11-28 11t-28-11L148-212q-12-12-12-28t12-28l104-104q11-11 28-11t28 11q11 11 11 28t-11 28l-36 36h528q17 0 28.5 11.5T840-240q0 17-11.5 28.5T800-200H272Zm88-440v-160q-33 0-56.5 23.5T280-720q0 33 23.5 56.5T360-640Zm0-80Z""", autoMirror = true)
        .also { _formatTextdirectionRToL = it }
private var _formatTextdirectionRToL: ImageVector? = null

/** Material Symbols `help`. */
val Icons.AutoMirrored.Outlined.HelpOutline: ImageVector
    get() = _helpOutline ?: symbolVector("AutoMirrored.Outlined.HelpOutline", """M513.5-254.5Q528-269 528-290t-14.5-35.5Q499-340 478-340t-35.5 14.5Q428-311 428-290t14.5 35.5Q457-240 478-240t35.5-14.5ZM480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Zm4-172q25 0 43.5 16t18.5 40q0 22-13.5 39T502-525q-23 20-40.5 44T444-427q0 14 10.5 23.5T479-394q15 0 25.5-10t13.5-25q4-21 18-37.5t30-31.5q23-22 39.5-48t16.5-58q0-51-41.5-83.5T484-720q-38 0-72.5 16T359-655q-7 12-4.5 25.5T368-609q14 8 29 5t25-17q11-15 27.5-23t34.5-8Z""", autoMirror = true)
        .also { _helpOutline = it }
private var _helpOutline: ImageVector? = null

/** Material Symbols `input`. */
val Icons.AutoMirrored.Outlined.Input: ImageVector
    get() = _input ?: symbolVector("AutoMirrored.Outlined.Input", """M160-160q-33 0-56.5-23.5T80-240v-80q0-17 11.5-28.5T120-360q17 0 28.5 11.5T160-320v80h640v-480H160v80q0 17-11.5 28.5T120-600q-17 0-28.5-11.5T80-640v-80q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Zm327-280H120q-17 0-28.5-11.5T80-480q0-17 11.5-28.5T120-520h367l-55-54q-12-11-11.5-27.5T432-630q12-12 28.5-12.5T489-631l123 123q12 12 12 28t-12 28L489-329q-12 12-28.5 12T432-329q-11-12-11.5-28.5T432-386l55-54Z""", autoMirror = true)
        .also { _input = it }
private var _input: ImageVector? = null

/** Material Symbols `insert_drive_file`. */
val Icons.AutoMirrored.Outlined.InsertDriveFile: ImageVector
    get() = _insertDriveFile ?: symbolVector("AutoMirrored.Outlined.InsertDriveFile", """M240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h287q16 0 30.5 6t25.5 17l194 194q11 11 17 25.5t6 30.5v447q0 33-23.5 56.5T720-80H240Zm280-560v-160H240v640h480v-440H560q-17 0-28.5-11.5T520-640ZM240-800v200-200 640-640Z""", autoMirror = true)
        .also { _insertDriveFile = it }
private var _insertDriveFile: ImageVector? = null

/** Material Symbols `keyboard_arrow_left`. */
val Icons.AutoMirrored.Outlined.KeyboardArrowLeft: ImageVector
    get() = _keyboardArrowLeft ?: symbolVector("AutoMirrored.Outlined.KeyboardArrowLeft", """m432-480 156 156q11 11 11 28t-11 28q-11 11-28 11t-28-11L348-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l184-184q11-11 28-11t28 11q11 11 11 28t-11 28L432-480Z""", autoMirror = true)
        .also { _keyboardArrowLeft = it }
private var _keyboardArrowLeft: ImageVector? = null

/** Material Symbols `keyboard_arrow_right`. */
val Icons.AutoMirrored.Outlined.KeyboardArrowRight: ImageVector
    get() = _keyboardArrowRight ?: symbolVector("AutoMirrored.Outlined.KeyboardArrowRight", """M504-480 348-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L404-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Z""", autoMirror = true)
        .also { _keyboardArrowRight = it }
private var _keyboardArrowRight: ImageVector? = null

/** Material Symbols `keyboard_return`. */
val Icons.AutoMirrored.Outlined.KeyboardReturn: ImageVector
    get() = _keyboardReturn ?: symbolVector("AutoMirrored.Outlined.KeyboardReturn", """m272-440 116 116q11 11 11 28t-11 28q-11 11-28 11t-28-11L148-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l184-184q11-11 28-11t28 11q11 11 11 28t-11 28L272-520h488v-120q0-17 11.5-28.5T800-680q17 0 28.5 11.5T840-640v120q0 33-23.5 56.5T760-440H272Z""", autoMirror = true)
        .also { _keyboardReturn = it }
private var _keyboardReturn: ImageVector? = null

/** Material Symbols `keyboard_tab`. */
val Icons.AutoMirrored.Outlined.KeyboardTab: ImageVector
    get() = _keyboardTab ?: symbolVector("AutoMirrored.Outlined.KeyboardTab", """M811.5-251.5Q800-263 800-280v-400q0-17 11.5-28.5T840-720q17 0 28.5 11.5T880-680v400q0 17-11.5 28.5T840-240q-17 0-28.5-11.5ZM567-440H120q-17 0-28.5-11.5T80-480q0-17 11.5-28.5T120-520h447L452-636q-11-11-11.5-27.5T452-692q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L508-268q-11 11-27.5 11T452-268q-12-12-12-28.5t12-28.5l115-115Z""", autoMirror = true)
        .also { _keyboardTab = it }
private var _keyboardTab: ImageVector? = null

/** Material Symbols `label`. */
val Icons.AutoMirrored.Outlined.Label: ImageVector
    get() = _label ?: symbolVector("AutoMirrored.Outlined.Label", """M160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h440q19 0 36 8.5t28 23.5l180 240q16 21 16 48t-16 48L664-192q-11 15-28 23.5t-36 8.5H160Zm0-80h440l180-240-180-240H160v480Zm310-240Z""", autoMirror = true)
        .also { _label = it }
private var _label: ImageVector? = null

/** Material Symbols `last_page`. */
val Icons.AutoMirrored.Outlined.LastPage: ImageVector
    get() = _lastPage ?: symbolVector("AutoMirrored.Outlined.LastPage", """M408-480 252-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L308-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Zm300.5-228.5Q720-697 720-680v400q0 17-11.5 28.5T680-240q-17 0-28.5-11.5T640-280v-400q0-17 11.5-28.5T680-720q17 0 28.5 11.5Z""", autoMirror = true)
        .also { _lastPage = it }
private var _lastPage: ImageVector? = null

/** Material Symbols `library_books`. */
val Icons.AutoMirrored.Outlined.LibraryBooks: ImageVector
    get() = _libraryBooks ?: symbolVector("AutoMirrored.Outlined.LibraryBooks", """M440-400h80q17 0 28.5-11.5T560-440q0-17-11.5-28.5T520-480h-80q-17 0-28.5 11.5T400-440q0 17 11.5 28.5T440-400Zm0-120h240q17 0 28.5-11.5T720-560q0-17-11.5-28.5T680-600H440q-17 0-28.5 11.5T400-560q0 17 11.5 28.5T440-520Zm0-120h240q17 0 28.5-11.5T720-680q0-17-11.5-28.5T680-720H440q-17 0-28.5 11.5T400-680q0 17 11.5 28.5T440-640ZM320-240q-33 0-56.5-23.5T240-320v-480q0-33 23.5-56.5T320-880h480q33 0 56.5 23.5T880-800v480q0 33-23.5 56.5T800-240H320Zm0-80h480v-480H320v480ZM160-80q-33 0-56.5-23.5T80-160v-520q0-17 11.5-28.5T120-720q17 0 28.5 11.5T160-680v520h520q17 0 28.5 11.5T720-120q0 17-11.5 28.5T680-80H160Zm160-720v480-480Z""", autoMirror = true)
        .also { _libraryBooks = it }
private var _libraryBooks: ImageVector? = null

/** Material Symbols `menu_book`. */
val Icons.AutoMirrored.Outlined.MenuBook: ImageVector
    get() = _menuBook ?: symbolVector("AutoMirrored.Outlined.MenuBook", """M260-320q47 0 91.5 10.5T440-278v-394q-41-24-87-36t-93-12q-36 0-71.5 7T120-692v396q35-12 69.5-18t70.5-6Zm260 42q44-21 88.5-31.5T700-320q36 0 70.5 6t69.5 18v-396q-33-14-68.5-21t-71.5-7q-47 0-93 12t-87 36v394Zm-66.5 93.5Q441-188 430-194q-39-23-82-34.5T260-240q-42 0-82.5 11T100-198q-21 11-40.5-1T40-234v-482q0-11 5.5-21T62-752q46-24 96-36t102-12q58 0 113.5 15T480-740q51-30 106.5-45T700-800q52 0 102 12t96 36q11 5 16.5 15t5.5 21v482q0 23-19.5 35t-40.5 1q-37-20-77.5-31T700-240q-45 0-88 11.5T530-194q-11 6-23.5 9.5T480-181q-14 0-26.5-3.5ZM280-494Zm280-115q0-9 6.5-18.5T581-640q29-10 58-15t61-5q20 0 39.5 2.5T778-651q9 2 15.5 10t6.5 18q0 17-11 25t-28 4q-14-3-29.5-4.5T700-600q-26 0-51 5t-48 13q-18 7-29.5-1T560-609Zm0 220q0-9 6.5-18.5T581-420q29-10 58-15t61-5q20 0 39.5 2.5T778-431q9 2 15.5 10t6.5 18q0 17-11 25t-28 4q-14-3-29.5-4.5T700-380q-26 0-51 4.5T601-363q-18 7-29.5-.5T560-389Zm0-110q0-9 6.5-18.5T581-530q29-10 58-15t61-5q20 0 39.5 2.5T778-541q9 2 15.5 10t6.5 18q0 17-11 25t-28 4q-14-3-29.5-4.5T700-490q-26 0-51 5t-48 13q-18 7-29.5-1T560-499Z""", autoMirror = true)
        .also { _menuBook = it }
private var _menuBook: ImageVector? = null

/** Material Symbols `open_in_new`. */
val Icons.AutoMirrored.Outlined.OpenInNew: ImageVector
    get() = _openInNew ?: symbolVector("AutoMirrored.Outlined.OpenInNew", """M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h240q17 0 28.5 11.5T480-800q0 17-11.5 28.5T440-760H200v560h560v-240q0-17 11.5-28.5T800-480q17 0 28.5 11.5T840-440v240q0 33-23.5 56.5T760-120H200Zm560-584L416-360q-11 11-28 11t-28-11q-11-11-11-28t11-28l344-344H600q-17 0-28.5-11.5T560-800q0-17 11.5-28.5T600-840h200q17 0 28.5 11.5T840-800v200q0 17-11.5 28.5T800-560q-17 0-28.5-11.5T760-600v-104Z""", autoMirror = true)
        .also { _openInNew = it }
private var _openInNew: ImageVector? = null

/** Material Symbols `playlist_add`. */
val Icons.AutoMirrored.Outlined.PlaylistAdd: ImageVector
    get() = _playlistAdd ?: symbolVector("AutoMirrored.Outlined.PlaylistAdd", """M160-320q-17 0-28.5-11.5T120-360q0-17 11.5-28.5T160-400h200q17 0 28.5 11.5T400-360q0 17-11.5 28.5T360-320H160Zm0-160q-17 0-28.5-11.5T120-520q0-17 11.5-28.5T160-560h360q17 0 28.5 11.5T560-520q0 17-11.5 28.5T520-480H160Zm0-160q-17 0-28.5-11.5T120-680q0-17 11.5-28.5T160-720h360q17 0 28.5 11.5T560-680q0 17-11.5 28.5T520-640H160Zm491.5 468.5Q640-183 640-200v-120H520q-17 0-28.5-11.5T480-360q0-17 11.5-28.5T520-400h120v-120q0-17 11.5-28.5T680-560q17 0 28.5 11.5T720-520v120h120q17 0 28.5 11.5T880-360q0 17-11.5 28.5T840-320H720v120q0 17-11.5 28.5T680-160q-17 0-28.5-11.5Z""", autoMirror = true)
        .also { _playlistAdd = it }
private var _playlistAdd: ImageVector? = null

/** Material Symbols `redo`. */
val Icons.AutoMirrored.Outlined.Redo: ImageVector
    get() = _redo ?: symbolVector("AutoMirrored.Outlined.Redo", """M648-560H396q-63 0-109.5 40T240-420q0 60 46.5 100T396-280h244q17 0 28.5 11.5T680-240q0 17-11.5 28.5T640-200H396q-97 0-166.5-63T160-420q0-94 69.5-157T396-640h252l-76-76q-11-11-11-28t11-28q11-11 28-11t28 11l144 144q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L628-428q-11 11-28 11t-28-11q-11-11-11-28t11-28l76-76Z""", autoMirror = true)
        .also { _redo = it }
private var _redo: ImageVector? = null

/** Material Symbols `rule`. */
val Icons.AutoMirrored.Outlined.Rule: ImageVector
    get() = _rule ?: symbolVector("AutoMirrored.Outlined.Rule", """m680-264-76 76q-11 11-28 11t-28-11q-11-11-11-28t11-28l76-76-76-76q-11-11-11-28t11-28q11-11 28-11t28 11l76 76 76-76q11-11 28-11t28 11q11 11 11 28t-11 28l-76 76 76 76q11 11 11 28t-11 28q-11 11-28 11t-28-11l-76-76Zm-26-369 142-142q12-12 28-11.5t28 12.5q11 12 11 28t-11 28L683-548q-12 12-28 12t-28-12l-86-86q-11-11-11-28t11-28q11-11 28-11t28 11l57 57ZM120-360h280q17 0 28.5 11.5T440-320q0 17-11.5 28.5T400-280H120q-17 0-28.5-11.5T80-320q0-17 11.5-28.5T120-360Zm0-320h280q17 0 28.5 11.5T440-640q0 17-11.5 28.5T400-600H120q-17 0-28.5-11.5T80-640q0-17 11.5-28.5T120-680Z""", autoMirror = true)
        .also { _rule = it }
private var _rule: ImageVector? = null

/** Material Symbols `segment`. */
val Icons.AutoMirrored.Outlined.Segment: ImageVector
    get() = _segment ?: symbolVector("AutoMirrored.Outlined.Segment", """M400-240q-17 0-28.5-11.5T360-280q0-17 11.5-28.5T400-320h400q17 0 28.5 11.5T840-280q0 17-11.5 28.5T800-240H400Zm0-200q-17 0-28.5-11.5T360-480q0-17 11.5-28.5T400-520h400q17 0 28.5 11.5T840-480q0 17-11.5 28.5T800-440H400ZM160-640q-17 0-28.5-11.5T120-680q0-17 11.5-28.5T160-720h640q17 0 28.5 11.5T840-680q0 17-11.5 28.5T800-640H160Z""", autoMirror = true)
        .also { _segment = it }
private var _segment: ImageVector? = null

/** Material Symbols `send`. */
val Icons.AutoMirrored.Outlined.Send: ImageVector
    get() = _send ?: symbolVector("AutoMirrored.Outlined.Send", """M792-443 176-183q-20 8-38-3.5T120-220v-520q0-22 18-33.5t38-3.5l616 260q25 11 25 37t-25 37ZM200-280l474-200-474-200v140l240 60-240 60v140Zm0 0v-400 400Z""", autoMirror = true)
        .also { _send = it }
private var _send: ImageVector? = null

/** Material Symbols `short_text`. */
val Icons.AutoMirrored.Outlined.ShortText: ImageVector
    get() = _shortText ?: symbolVector("AutoMirrored.Outlined.ShortText", """M200-360q-17 0-28.5-11.5T160-400q0-17 11.5-28.5T200-440h320q17 0 28.5 11.5T560-400q0 17-11.5 28.5T520-360H200Zm0-160q-17 0-28.5-11.5T160-560q0-17 11.5-28.5T200-600h560q17 0 28.5 11.5T800-560q0 17-11.5 28.5T760-520H200Z""", autoMirror = true)
        .also { _shortText = it }
private var _shortText: ImageVector? = null

/** Material Symbols `sort`. */
val Icons.AutoMirrored.Outlined.Sort: ImageVector
    get() = _sort ?: symbolVector("AutoMirrored.Outlined.Sort", """M160-240q-17 0-28.5-11.5T120-280q0-17 11.5-28.5T160-320h160q17 0 28.5 11.5T360-280q0 17-11.5 28.5T320-240H160Zm0-200q-17 0-28.5-11.5T120-480q0-17 11.5-28.5T160-520h400q17 0 28.5 11.5T600-480q0 17-11.5 28.5T560-440H160Zm0-200q-17 0-28.5-11.5T120-680q0-17 11.5-28.5T160-720h640q17 0 28.5 11.5T840-680q0 17-11.5 28.5T800-640H160Z""", autoMirror = true)
        .also { _sort = it }
private var _sort: ImageVector? = null

/** Material Symbols `sticky_note_2`. */
val Icons.AutoMirrored.Outlined.StickyNote2: ImageVector
    get() = _stickyNote2 ?: symbolVector("AutoMirrored.Outlined.StickyNote2", """M200-200h360v-160q0-17 11.5-28.5T600-400h160v-360H200v560Zm0 80q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v367q0 16-6 30.5T817-337L623-143q-11 11-25.5 17t-30.5 6H200Zm240-280H320q-17 0-28.5-11.5T280-440q0-17 11.5-28.5T320-480h120q17 0 28.5 11.5T480-440q0 17-11.5 28.5T440-400Zm200-160H320q-17 0-28.5-11.5T280-600q0-17 11.5-28.5T320-640h320q17 0 28.5 11.5T680-600q0 17-11.5 28.5T640-560ZM200-200v-560 560Z""", autoMirror = true)
        .also { _stickyNote2 = it }
private var _stickyNote2: ImageVector? = null

/** Material Symbols `subject`. */
val Icons.AutoMirrored.Outlined.Subject: ImageVector
    get() = _subject ?: symbolVector("AutoMirrored.Outlined.Subject", """M200-200q-17 0-28.5-11.5T160-240q0-17 11.5-28.5T200-280h320q17 0 28.5 11.5T560-240q0 17-11.5 28.5T520-200H200Zm0-160q-17 0-28.5-11.5T160-400q0-17 11.5-28.5T200-440h560q17 0 28.5 11.5T800-400q0 17-11.5 28.5T760-360H200Zm0-160q-17 0-28.5-11.5T160-560q0-17 11.5-28.5T200-600h560q17 0 28.5 11.5T800-560q0 17-11.5 28.5T760-520H200Zm0-160q-17 0-28.5-11.5T160-720q0-17 11.5-28.5T200-760h560q17 0 28.5 11.5T800-720q0 17-11.5 28.5T760-680H200Z""", autoMirror = true)
        .also { _subject = it }
private var _subject: ImageVector? = null

/** Material Symbols `text_snippet`. */
val Icons.AutoMirrored.Outlined.TextSnippet: ImageVector
    get() = _textSnippet ?: symbolVector("AutoMirrored.Outlined.TextSnippet", """M200-200h560v-367L567-760H200v560Zm0 80q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h367q16 0 30.5 6t25.5 17l194 194q11 11 17 25.5t6 30.5v367q0 33-23.5 56.5T760-120H200Zm120-160h320q17 0 28.5-11.5T680-320q0-17-11.5-28.5T640-360H320q-17 0-28.5 11.5T280-320q0 17 11.5 28.5T320-280Zm0-160h320q17 0 28.5-11.5T680-480q0-17-11.5-28.5T640-520H320q-17 0-28.5 11.5T280-480q0 17 11.5 28.5T320-440Zm0-160h200q17 0 28.5-11.5T560-640q0-17-11.5-28.5T520-680H320q-17 0-28.5 11.5T280-640q0 17 11.5 28.5T320-600ZM200-200v-560 560Z""", autoMirror = true)
        .also { _textSnippet = it }
private var _textSnippet: ImageVector? = null

/** Material Symbols `trending_up`. */
val Icons.AutoMirrored.Outlined.TrendingUp: ImageVector
    get() = _trendingUp ?: symbolVector("AutoMirrored.Outlined.TrendingUp", """M108-255q-12-12-11.5-28.5T108-311l211-214q23-23 57-23t57 23l103 104 208-206h-64q-17 0-28.5-11.5T640-667q0-17 11.5-28.5T680-707h160q17 0 28.5 11.5T880-667v160q0 17-11.5 28.5T840-467q-17 0-28.5-11.5T800-507v-64L593-364q-23 23-57 23t-57-23L376-467 164-255q-11 11-28 11t-28-11Z""", autoMirror = true)
        .also { _trendingUp = it }
private var _trendingUp: ImageVector? = null

/** Material Symbols `undo`. */
val Icons.AutoMirrored.Outlined.Undo: ImageVector
    get() = _undo ?: symbolVector("AutoMirrored.Outlined.Undo", """M320-200q-17 0-28.5-11.5T280-240q0-17 11.5-28.5T320-280h244q63 0 109.5-40T720-420q0-60-46.5-100T564-560H312l76 76q11 11 11 28t-11 28q-11 11-28 11t-28-11L188-572q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l144-144q11-11 28-11t28 11q11 11 11 28t-11 28l-76 76h252q97 0 166.5 63T800-420q0 94-69.5 157T564-200H320Z""", autoMirror = true)
        .also { _undo = it }
private var _undo: ImageVector? = null

/** Material Symbols `view_list`. */
val Icons.AutoMirrored.Outlined.ViewList: ImageVector
    get() = _viewList ?: symbolVector("AutoMirrored.Outlined.ViewList", """M360-240h440v-107H360v107ZM160-613h120v-107H160v107Zm0 187h120v-107H160v107Zm0 186h120v-107H160v107Zm200-186h440v-107H360v107Zm0-187h440v-107H360v107ZM160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Z""", autoMirror = true)
        .also { _viewList = it }
private var _viewList: ImageVector? = null

/** Material Symbols `volume_off`. */
val Icons.AutoMirrored.Outlined.VolumeOff: ImageVector
    get() = _volumeOff ?: symbolVector("AutoMirrored.Outlined.VolumeOff", """M671-177q-11 7-22 13t-23 11q-15 7-30.5 0T574-176q-6-15 1.5-29.5T598-227q4-2 7.5-4t7.5-4L480-368v111q0 27-24.5 37.5T412-228L280-360H160q-17 0-28.5-11.5T120-400v-160q0-17 11.5-28.5T160-600h88L84-764q-11-11-11-28t11-28q11-11 28-11t28 11l680 680q11 11 11 28t-11 28q-11 11-28 11t-28-11l-93-93Zm89-304q0-83-44-151.5T598-735q-15-7-22-21.5t-2-29.5q6-16 21.5-23t31.5 0q97 43 155 131t58 197q0 33-6 65.5T817-353q-8 22-24.5 27.5t-30.5.5q-14-5-22.5-18t-.5-30q11-26 16-52.5t5-55.5ZM591-623q33 21 51 63t18 80v10q0 5-1 10-2 13-14 17t-22-6l-51-51q-6-6-9-13.5t-3-15.5v-77q0-12 10.5-17.5t20.5.5Zm-201-59q-6-6-6-14t6-14l22-22q19-19 43.5-8.5T480-703v63q0 14-12 19t-22-5l-56-56Zm10 328v-94l-72-72H200v80h114l86 86Zm-36-130Z""", autoMirror = true)
        .also { _volumeOff = it }
private var _volumeOff: ImageVector? = null

/** Material Symbols `volume_up`. */
val Icons.AutoMirrored.Outlined.VolumeUp: ImageVector
    get() = _volumeUp ?: symbolVector("AutoMirrored.Outlined.VolumeUp", """M760-481q0-83-44-151.5T598-735q-15-7-22-21.5t-2-29.5q6-16 21.5-23t31.5 0q97 43 155 131.5T840-481q0 108-58 196.5T627-153q-16 7-31.5 0T574-176q-5-15 2-29.5t22-21.5q74-34 118-102.5T760-481ZM280-360H160q-17 0-28.5-11.5T120-400v-160q0-17 11.5-28.5T160-600h120l132-132q19-19 43.5-8.5T480-703v446q0 27-24.5 37.5T412-228L280-360Zm380-120q0 42-19 79.5T591-339q-10 6-20.5.5T560-356v-250q0-12 10.5-17.5t20.5.5q31 25 50 63t19 80ZM400-606l-86 86H200v80h114l86 86v-252ZM300-480Z""", autoMirror = true)
        .also { _volumeUp = it }
private var _volumeUp: ImageVector? = null

/** Material Symbols `wrap_text`. */
val Icons.AutoMirrored.Outlined.WrapText: ImageVector
    get() = _wrapText ?: symbolVector("AutoMirrored.Outlined.WrapText", """M200-460q-17 0-28.5-11.5T160-500q0-17 11.5-28.5T200-540h490q63 0 106.5 43.5T840-390q0 63-43.5 106.5T690-240h-96l22 22q12 12 11.5 28T616-162q-12 12-28.5 12.5T559-161l-91-91q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l91-91q12-12 28.5-12t28.5 12q11 12 11.5 28.5T616-342l-22 22h96q29 0 49.5-20.5T760-390q0-29-20.5-49.5T690-460H200Zm0 220q-17 0-28.5-11.5T160-280q0-17 11.5-28.5T200-320h120q17 0 28.5 11.5T360-280q0 17-11.5 28.5T320-240H200Zm0-440q-17 0-28.5-11.5T160-720q0-17 11.5-28.5T200-760h560q17 0 28.5 11.5T800-720q0 17-11.5 28.5T760-680H200Z""", autoMirror = true)
        .also { _wrapText = it }
private var _wrapText: ImageVector? = null
