#!/usr/bin/env python3
"""Regenerate NativeLetterTable.kt: each Latin-script language's own letters.

Android hides ICU's exemplar sets, so the table is baked in. For every
LanguageDef with script LATIN, take CLDR's main exemplar set (its full locale,
else its primary subtag) and keep the lowercase non-ASCII Latin letters.

    curl -sL https://registry.npmjs.org/cldr-misc-full/-/cldr-misc-full-48.2.0.tgz | tar xz -C /tmp
    python3 scripts/gen_native_letters.py /tmp/package
"""
import glob, json, os, re, sys, unicodedata

cldr = sys.argv[1]
SRC = 'core/language/src/main/java/com/wasimaster/wmkeyboard/core/script'
OUT = 'feature/ime/src/main/java/com/wasimaster/wmkeyboard/ime/ui/NativeLetterTable.kt'


def latin_tags():
    tags = set()
    for f in glob.glob(f'{SRC}/*.kt'):
        for blk in open(f, encoding='utf-8').read().split('LanguageDef(')[1:]:
            script = re.search(r'script = ScriptId\.(\w+)', blk)
            tag = re.search(r'localeTag = "([^"]+)"', blk)
            if script and tag and script.group(1) == 'LATIN':
                tags.add(tag.group(1))
    return sorted(tags)


def unicode_set(text):
    """The elements of a CLDR exemplar UnicodeSet: [a b c-e {ch} \\u00E9]."""
    s, out, i = text.strip()[1:-1], [], 0

    def char(i):
        if s[i] == '\\':
            if s[i + 1] == 'u':
                return chr(int(s[i + 2:i + 6], 16)), i + 6
            return s[i + 1], i + 2
        return s[i], i + 1

    while i < len(s):
        if s[i] == ' ':
            i += 1
        elif s[i] == '{':
            j = s.index('}', i)
            out.append(s[i + 1:j])
            i = j + 1
        else:
            c, i = char(i)
            if i < len(s) - 1 and s[i] == '-':
                end, i = char(i + 1)
                out.extend(chr(k) for k in range(ord(c), ord(end) + 1))
            else:
                out.append(c)
    return out


def letters(tag):
    for loc in (tag, tag.split('-')[0]):
        path = f'{cldr}/main/{loc}/characters.json'
        if os.path.exists(path):
            chars = json.load(open(path, encoding='utf-8'))['main'][loc]['characters']
            found = []
            for g in unicode_set(chars['exemplarCharacters']):
                g = unicodedata.normalize('NFC', g.lower())
                if (len(g) == 1 and ord(g) > 127 and unicodedata.category(g).startswith('L')
                        and 'LATIN' in unicodedata.name(g, '') and g not in found):
                    found.append(g)
            return ''.join(found)
    return ''


rows = [(t, letters(t)) for t in latin_tags()]
rows = [(t, l) for t, l in rows if l]
version = json.load(open(f'{cldr}/package.json'))['version']
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('package com.wasimaster.wmkeyboard.ime.ui\n\n')
    f.write(f'// Generated by scripts/gen_native_letters.py from CLDR {version} (cldr-misc-full).\n')
    f.write('// Do not edit by hand: rerun the script.\n\n')
    f.write('/**\n * Each Latin-script language\'s letters beyond a-z, by [LanguageDef.localeTag]:\n')
    f.write(' * the non-ASCII letters of its CLDR main exemplar set, lowercased. A\n')
    f.write(' * language whose alphabet is plain a-z, English among them, has no entry.\n */\n')
    f.write('internal val NativeLetterTable: Map<String, String> = mapOf(\n')
    for t, l in rows:
        f.write(f'    "{t}" to "{l}",\n')
    f.write(')\n')
print(f'{len(rows)} languages written to {OUT}')
