/**
 * The plugin editor's words, verbatim from the app's strings_plugin_ide.xml,
 * strings_code_editor.xml and the plugin module's strings, so the web editor
 * says exactly what the phone says.
 */
export const S = {
	// Ways in and the drafts list
	projectsTitle: 'Plugin editor',
	newTitle: 'New plugin',
	newSubtitle: 'Start from a small plugin that works',
	newNameHint: 'Name',
	newDefaultName: 'My plugin',
	newAction: 'Create',
	newError: 'The draft could not be made. The editor holds 20 drafts at most.',
	draftsTitle: 'Drafts',
	draftsEmpty: 'No drafts yet',
	draftUntitled: 'Plugin with no name',
	draftEdited: (ago: string) => `Changed ${ago}`,
	draftPublished: (version: string, ago: string) => `Version ${version} installed. Changed ${ago}`,
	deleteDraftDesc: 'Delete the draft',
	deleteDraftTitle: 'Delete the draft',
	deleteDraftBody: 'The code, its saved versions and its test data are deleted. An installed plugin stays installed.',
	missing: 'This draft is not on the device',
	duplicateDraftDesc: 'Duplicate the draft',

	// The code screen
	runDesc: 'Run the plugin',
	stopDesc: 'Stop the plugin',
	publishDesc: 'Install the plugin',
	moreDesc: 'More actions',
	formatAction: 'Format the code',
	detailsAction: 'Name and permissions',
	versionAction: 'Save a version',
	versionSaved: 'Version saved',
	versionSame: 'The code is the same as the last saved version',
	saved: 'The draft is saved',
	published: (version: string) => `Version ${version} is installed`,
	updated: (version: string) => `The plugin is updated to version ${version}`,
	publishFailed: 'The plugin could not be installed',
	tooMany: 'You have the largest number of plugins there can be. Uninstall one first.',
	detailsTitle: 'Plugin details',
	/** The web editor's own pane, not a string of the app's. */
	detailsLabel: 'Details',
	detailsName: 'Name',
	detailsId: 'Identifier',
	detailsVersion: 'Version',
	detailsAuthor: 'Author',
	detailsDescription: 'Description',
	permissionStorage: 'Save data on your device',

	// The panel under the code
	previewLabel: 'Preview',
	consoleLabel: 'Console',
	problemsLabel: 'Problems',
	outlineLabel: 'Outline',
	eventsLabel: 'Events',
	storageLabel: 'Storage',
	previewEmpty: 'Run the plugin to see its panel',
	usage: (used: string, limit: string) => `The last draw used ${used} of ${limit} instructions`,
	consoleEmpty: 'Nothing is printed yet',
	problemsEmpty: 'The checks find no problems',
	outlineEmpty: 'No named functions yet',
	severityError: 'Error',
	severityWarning: 'Warning',
	severityInfo: 'Note',
	consoleClear: 'Clear',
	consoleStarted: 'The plugin started',
	consoleCancelled: 'A newer run replaced this run',
	lineLabel: (line: number) => `Line ${line}`,
	preludeLineLabel: (line: number) => `Prelude line ${line}`,
	copied: 'Copied',
	autoRunLabel: 'Run as you type',
	budgetHistoryDesc: 'How many instructions the last draws used',
	eventsEmpty: 'Run the plugin to send events to its buttons, switches, boxes and tabs.',
	eventClick: (id: string) => `Press ${id}`,
	eventClickDisabled: (id: string) => `Press ${id}, turned off`,
	eventToggleOn: (id: string) => `Switch ${id} on`,
	eventToggleOff: (id: string) => `Switch ${id} off`,
	eventTab: (id: string, page: number) => `Page ${page} of ${id}`,
	eventInputLabel: (id: string) => `Text for ${id}`,
	eventSend: 'Send',
	eventCustomTitle: 'Any event',
	eventIdLabel: 'Id',
	eventValueLabel: 'Value',
	eventReplay: (n: number) => (n === 1 ? `Send ${n} earlier event again` : `Send ${n} earlier events again`),
	storageUndeclared: 'The manifest does not declare the storage permission, so the plugin has no storage.',
	storageUnavailable: 'Storage is not available until the phone is unlocked.',
	storageEmpty: 'Nothing is stored yet',
	storageBusy: 'The plugin is running. Changes wait until it finishes.',
	storageKey: 'Key',
	storageValue: 'Value',
	storageSave: 'Save',
	storageRemoveDesc: (key: string) => `Remove ${key}`,
	storageRefused: (why: string) => `Not saved: ${why}`,
	storageScopePreview: 'Preview',
	storageScopeInstalled: 'Installed',
	textLarger: 'Larger text',
	textSmaller: 'Smaller text',
	docMore: 'Show the whole description',
	docLess: 'Show less',
	preludeTitle: 'The prelude',
	preludeCaption: 'Every plugin runs this code before its own script, to make the ui helpers. It cannot be changed.',
	foldAll: 'Fold every block',
	unfoldAll: 'Unfold every block',
	codeKeysAction: 'Code keys',

	// Finding and renaming
	findAction: 'Find and replace',
	goToLineAction: 'Go to line',
	definitionAction: 'Go to definition',
	renameAction: 'Rename',
	noDefinition: 'The script does not declare this name',
	noRename: 'Put the caret on a name the script declares. Rename works when the script has no syntax errors.',
	renameTitle: (name: string) => `Rename ${name}`,
	renameLabel: 'New name',
	renameCount: (n: number) => (n === 1 ? `Changes ${n} place` : `Changes ${n} places`),
	renameNotAName: 'Use letters, digits and underscores, with no digit first.',
	renameKeyword: 'This is a Lua keyword.',
	renameTaken: 'Another name with this spelling is already in use here.',

	// Templates, files
	templatesTitle: 'Start from',
	templateBlankName: 'A blank plugin',
	templateBlankDescription: 'A button that counts presses. The smallest plugin that works.',
	templateTextToolsName: 'Text tools',
	templateTextToolsDescription: 'Changes the case of the text typed into its box, encodes it and counts it',
	templateCipherName: 'Cipher tool',
	templateCipherDescription: 'Caesar and Vigenère ciphers. The plugin the getting started guide builds.',
	templateTodoName: 'Todo list',
	templateTodoDescription: 'A list the plugin keeps on this device with the storage permission',
	templateKitchenSinkName: 'Every widget',
	templateKitchenSinkDescription: 'Each widget and each event in one panel, to copy from',
	importTitle: 'Open a plugin file',
	importSubtitle: 'Edit a .wmplugin file as a new draft. Nothing is installed.',
	importNotAPlugin: 'This file is not a plugin',
	importFailed: 'The keyboard cannot read this file',
	exportAction: 'Save as a file',
	exportSaved: 'The plugin file is saved',
	exportFailed: 'The keyboard cannot save the file',
	exportProblems: 'Correct the name and permissions before you save a file',

	// Versions
	versionsAction: 'Versions',
	versionsTitle: 'Versions',
	versionsEmpty: 'No versions yet. The editor keeps one when you save a version, when you install, and every few minutes while you work.',
	reasonManual: 'Saved by you',
	reasonPeriodic: 'Kept while you worked',
	reasonBeforeRestore: 'Kept before a restore',
	reasonPublish: 'Installed',
	reasonImport: 'Opened from a file',
	versionLines: (n: number) => (n === 1 ? `${n} line` : `${n} lines`),
	versionDiffTitle: (when: string) => `Version from ${when}`,
	versionDiffCaption: 'If you restore this version, lines marked + come back and lines marked - go.',
	versionSameAsNow: 'This version is the same as the code now.',
	unchangedLines: (n: number) => (n === 1 ? `${n} line is the same` : `${n} lines are the same`),
	restoreAction: 'Restore',
	restored: 'The version is restored. Undo brings back the code before it.',
	restoreFailed: 'The keyboard cannot restore this version',

	// The code field itself (strings_code_editor.xml)
	redoDesc: 'Redo',
	undoDesc: 'Undo',
	wrapOnDesc: 'Wrap long lines',
	wrapOffDesc: 'Do not wrap long lines',
	position: (line: number, column: number) => `Line ${line}, column ${column}`,
	findLabel: 'Find',
	replaceLabel: 'Replace with',
	findCount: (n: number, of: number) => `${n} of ${of}`,
	findNone: 'No results',
	findInvalid: 'The pattern is not valid',
	findCaseDesc: 'Match case',
	findWordDesc: 'Whole words only',
	findRegexDesc: 'Use a regular expression',
	findPreviousDesc: 'Previous result',
	findNextDesc: 'Next result',
	findCloseDesc: 'Close find',
	replaceToggle: 'Replace',
	replaceOne: 'Replace',
	replaceAll: 'Replace all',
	goToLineTitle: 'Go to line',
	goToLineLabel: 'Line number',
	goToLineError: (lines: number) => `Enter a line from 1 to ${lines}`,
	goToLineGo: 'Go',
	keyIndentDesc: 'Indent the line. Hold to outdent it.',
	keysPageDesc: 'Show the other keys',
	keyLeftDesc: 'Move the caret left. Slide to move it further.',
	keyRightDesc: 'Move the caret right. Slide to move it further.',
	commandSuggest: 'Suggest',
	commandUndo: 'Undo',
	commandRedo: 'Redo',
	commandComment: 'Comment',
	commandDuplicate: 'Duplicate',
	commandLineUp: 'Line up',
	commandLineDown: 'Line down',
	commandSelectWord: 'Select word',
	commandSelectLine: 'Select line',
	commandFind: 'Find',
	commandFormat: 'Format',
	commandBlockStart: 'Block start',
	commandBlockEnd: 'Block end',
	keysTitle: 'Code keys',
	keysShowLabel: 'Show the row of code keys',
	keysCaption: 'Drag a key by its handle to move it. Clear its box to hide it.',
	keysReset: 'Reset',
	keyShowDesc: (key: string) => `Show ${key}`,

	// Common words
	back: 'Back',
	cancel: 'Cancel',
	close: 'Close',
	delete: 'Delete',
	done: 'Done',
	save: 'Save',
	copy: 'Copy',
	paste: 'Paste',
	insert: 'Insert',
	tabDefaultTitle: (n: number) => `Tab ${n}`,

	// The plugin module's own words (core/plugins strings)
	rejectBadId: 'This plugin has an id that is not valid. An id is 3 to 64 characters long. An id can contain lowercase letters, numbers, dots, dashes and underscores.',
	rejectNoName: 'This plugin does not have a name.',
	rejectNoVersion: (name: string) => `“${name}” does not say which version it is.`,
	rejectScriptTooLarge: (name: string, kb: number) => `“${name}” has a script larger than ${kb} KB.`,
	errorNoRender: 'This plugin has no render() function.',
	errorScriptFailed: 'The script failed.',
	stoppedInstructions: 'This plugin did too much work at one time. The app stopped it.',
	stoppedDeadline: 'This plugin took too long. The app stopped it.',
	stoppedCancelled: 'The app stopped this plugin.',
	stoppedRecursion: 'This plugin called itself too many times. The app stopped it.',
	stoppedUnexpected: 'This plugin stopped unexpectedly.',
	repairNotAWidget: 'A widget list contained something that is not a widget.',
	repairTooDeep: 'Some widgets were nested too deeply to draw.',
	repairTooManyWidgets: (n: number) => `This plugin asked for more than ${n} widgets. The app dropped the rest.`,
	repairNoType: 'A widget did not say what kind it is.',
	repairUnknownType: (type: string) => `This build does not know the widget type “${type}”.`,
	repairTabsNoPages: 'A tab strip had no pages.',
	repairTooManyTabs: (n: number) => `Only the first ${n} tabs are shown.`,
	repairTextBudget: 'This plugin asked to draw too much text. The app left some out.',
	repairTextShortened: 'Some text was too long to draw. The app shortened it.',
};

/** Android's DateUtils.getRelativeTimeSpanString with a minute's resolution, in English. */
export function relativeTime(at: number, now = Date.now()): string {
	const diff = now - at;
	const past = diff >= 0;
	const abs = Math.abs(diff);
	const minute = 60_000;
	const hour = 60 * minute;
	const day = 24 * hour;
	if (abs < minute) return past ? '0 minutes ago' : 'in 0 minutes';
	let n: number;
	let unit: string;
	if (abs < hour) {
		n = Math.floor(abs / minute);
		unit = 'minute';
	} else if (abs < day) {
		n = Math.floor(abs / hour);
		unit = 'hour';
	} else if (abs < 7 * day) {
		n = Math.floor(abs / day);
		unit = 'day';
	} else {
		return new Date(at).toLocaleDateString();
	}
	const words = `${n} ${unit}${n === 1 ? '' : 's'}`;
	return past ? `${words} ago` : `in ${words}`;
}
