/**
 * The breadcrumb trail, built once and used twice.
 *
 * `PageTitle.astro` renders it for the reader and `Head.astro` publishes it as
 * `BreadcrumbList` JSON-LD. Both used to build their own: astro-breadcrumbs
 * emitted a trail derived from the sidebar, and the structured data derived a
 * second one from the section list, so every page shipped two BreadcrumbLists
 * that disagreed about the middle crumb. Google reads whichever it likes, and
 * its own guidance is that the markup has to match the visible trail — so
 * there is one function, and astro-breadcrumbs' schema is turned off.
 *
 * The trail comes from Starlight's sidebar rather than from the URL, because
 * the sidebar knows each page's real title ("Keys & typing basics", not
 * "Basics") and because none of the section directories have an index page: a
 * URL-derived trail would link every middle crumb to a 404. A section crumb
 * points at the first page in that section instead.
 */

import { SITE_TITLE } from '../site.mjs';

type Route = typeof Astro.locals.starlightRoute;
type SidebarEntry = Route['sidebar'][number];
type SidebarGroup = Extract<SidebarEntry, { type: 'group' }>;

export interface Crumb {
	text: string;
	href: string;
}

/** First actual page inside a group — where that group's crumb points. */
function firstLink(entries: SidebarEntry[]): string | undefined {
	for (const item of entries) {
		if (item.type === 'link') return item.href;
		const nested = firstLink(item.entries);
		if (nested) return nested;
	}
	return undefined;
}

/** The chain of groups wrapping the page Starlight flagged as current. */
function groupTrail(entries: SidebarEntry[], ancestors: SidebarGroup[] = []): SidebarGroup[] | undefined {
	for (const item of entries) {
		if (item.type === 'link') {
			if (item.isCurrent) return ancestors;
		} else {
			const found = groupTrail(item.entries, [...ancestors, item]);
			if (found) return found;
		}
	}
	return undefined;
}

/**
 * Groups autogenerated from a directory take the directory name verbatim, so
 * `reference/settings` arrives as "settings". Labels written out in the
 * sidebar config ("Getting started") are already cased and pass through
 * untouched.
 */
const label = (text: string) => text.charAt(0).toUpperCase() + text.slice(1);

export function buildCrumbs(route: Route, pathname: string): Crumb[] {
	return [
		{ text: SITE_TITLE, href: '/' },
		...(groupTrail(route.sidebar) ?? []).flatMap((group) => {
			const href = firstLink(group.entries);
			return href ? [{ text: label(group.label), href }] : [];
		}),
		{ text: String(route.entry.data.title), href: pathname },
	];
}
